In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES']="1"
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from collections import defaultdict
from itertools import combinations
from itertools import chain
from collections import namedtuple
import pickle
import tensorflow as tf
import tflearn
import matplotlib.pyplot as plt
import os.path
import shutil
import inspect
from nn_lib import *
from train_procedures import *
from train_utils import *
from breakhis_utils import *
import matplotlib.pyplot as plt
import json
from pprint import pprint
from copy import copy
from sklearn.metrics import confusion_matrix
import seaborn as sns
np.random.seed(1997)
%load_ext autoreload
%autoreload 2

In [2]:
data_set_total=load_breakhis_data(400)

7908

In [3]:
cifar100_total=load_cifar100_data(normalize=False)

In [4]:
hela10_total=load_hela10_data(400)

NameError: name 'load_hela10_data' is not defined

In [1]:
data_set_total['X_train'].shape

NameError: name 'data_set_total' is not defined

In [31]:
hyper_params={'beta':1e-5,
              'initial_lr':0.1,
              'train_batch_size':64,
              'test_batch_size':64,
              'lr_reduction_rate':10,
              'lr_reduction_epoch':[4,7],
              'use_fixedsize_exemplar':True,
              'exemplar_set_size':1600,
              'final_train_epochs':5,
              'se':True,
              'primary_exemplar':'svm_exemplar',
              'train_method':'train_plain',
              'sample_weight':1e-5,
              'shuffle_class_ord':False,
              'optimizer':'momentum',
              'ewc_lambda':1e-5,
              'loss_function':'softmax_cross_entropy_with_logits'}
fixed_params={'dataset':'breakhis',
              'net_type':'ResNet18',
              'random_seed':1997,
              'total_num_classes':8,
              'base_dir':'./breakhis_temp',
              'class_batch_size':2,
              'use_theoretical_mean':True}

In [32]:
data_dict_total=dict(X_train=data_set_total['X_train'],
                     Y_train=data_set_total['fine_labels_train'],
                     X_test=data_set_total['X_test'],
                     Y_test=data_set_total['fine_labels_test'])

In [33]:
# data_dict_total=dict(X_train=cifar100_total['X_train'],
#                      Y_train=cifar100_total['Y_train'],
#                      X_test=cifar100_total['X_test'],
#                      Y_test=cifar100_total['Y_test'])

In [34]:
tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)

log_prob
log_prob
log_prob


In [35]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=1.0)
sess=tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

In [36]:
fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict_total,sess,resume=False,
        save_session=False,save_session_freq=1,save_params=True,evaluation_metric='top1_accuracy',save_history=True,
        num_epochs=10,num_iterations=4,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=True)

{'base_dir': './breakhis_temp',
 'class_batch_size': 2,
 'dataset': 'breakhis',
 'net_type': 'ResNet18',
 'random_seed': 1997,
 'total_num_classes': 8,
 'use_theoretical_mean': True}
{'beta': 1e-05,
 'ewc_lambda': 1,
 'exemplar_set_size': 1600,
 'final_train_epochs': 5,
 'initial_lr': 0.001,
 'loss_function': 'softmax_cross_entropy_with_logits',
 'lr_reduction_epoch': [10, 20, 30],
 'lr_reduction_rate': 5,
 'optimizer': 'momentum',
 'primary_exemplar': 'svm_exemplar',
 'sample_weight': 1,
 'se': True,
 'shuffle_class_ord': False,
 'test_batch_size': 64,
 'train_batch_size': 64,
 'train_method': 'train_plain',
 'use_fixedsize_exemplar': True}
./breakhis_temp already exists, override?y
data_dict_current: 5074
Counter({0: 2537, 1: 2537})
data_dict_current_weight:
Counter({1: 5074})
data_dict_total: 400
Counter({0: 50, 1: 50, 2: 50, 3: 50, 4: 50, 5: 50, 6: 50, 7: 50})
===========Iteration 1=============
Using classes [0, 1]
augmentation: 2


/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn

augmentation: 2
Class batch pretrain evaluation (plain method)
	Train loss: 2.113902
	Train class loss: 2.057072
	Train reg loss: 0.000000
	Validation loss: 2.114996
	Validation class loss: 2.058166
	Validation reg loss: 0.056830
	Top1 train accuracy: 0.000000
	Top5 train accuracy: 0.512022
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.500000
[[ 0  0 50]
 [ 0  0 50]
 [ 0  0  0]]
augmentation: 2
augmentation: 2
Epoch 1
	Train loss: 0.603844
	Train class loss: 0.547012
	Train reg loss: 0.056832
	Validation loss: 0.636160
	Validation class loss: 0.579326
	Validation reg loss: 0.056834
	Top1 train accuracy: 0.787579
	Top5 train accuracy: 0.970926
	Top1 validation accuracy: 0.810000
	Top5 validation accuracy: 0.990000
[[36 14]
 [ 5 45]]
network nan test after epoch
mbi=4366983680
epoch 1, global step 1, time 99.957123
saving model parameters...
augmentation: 2
augmentation: 2
augmentation: 2
On iteration 1
Plain evaluation before retrain
	Best top1 validation accuracy: 0.

augmentation: 2
augmentation: 2
augmentation: 2
augmentation: 2
SVM evaluation
	Best top1 validation accuracy: 0.780000
	Best top1 cumul accuracy: 0.670000
	Best top1 ori accuracy: 0.560000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       0.77      0.98      0.86        50
          1       0.88      0.14      0.24        50
          2       0.58      0.86      0.69        50
          3       0.65      0.70      0.67        50

avg / total       0.72      0.67      0.62       200

augmentation: 2
augmentation: 2
augmentation: 2
Exemplar mean evaluation
	Best top1 validation accuracy: 0.560000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.575000
	Best top5 cumul accuracy: 1.000000
	Best top1 ori accuracy: 0.590000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       0.76      0.88      0.81        50
          1       0.38 

augmentation: 2
augmentation: 2
augmentation: 2
augmentation: 2
Theoretical mean evaluation
	Best top1 validation accuracy: 0.760000
	Best top5 validation accuracy: 0.980000
	Best top1 cumul accuracy: 0.536667
	Best top5 cumul accuracy: 0.990000
	Best top1 ori accuracy: 0.400000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       0.59      0.58      0.59        50
          1       0.33      0.22      0.27        50
          2       0.49      0.46      0.47        50
          3       0.48      0.44      0.46        50
          4       0.59      0.64      0.62        50
          5       0.62      0.88      0.73        50

avg / total       0.52      0.54      0.52       300

computing fisher information
augmentation: 2
conv_1/W:2.603281e+01
batch_norm_1/scale:2.938816e-01
resconv1_2a/W:2.506683e-01
batch_norm_resconv1_2a/scale:4.944172e-02
resconv2_2a/W:2.544680e-01
batch_norm_resconv2_2a/scale:8.7

augmentation: 2
augmentation: 2
Final evaluation on all classes (plain method)
	Train loss: 3.553924
	Train class loss: 3.497100
	Train reg loss: 0.174813
	Validation loss: 3.548928
	Validation class loss: 3.492103
	Validation reg loss: 0.056824
	Top1 train accuracy: 0.174813
	Top5 train accuracy: 0.742363
	Top1 validation accuracy: 0.172500
	Top5 validation accuracy: 0.740000
augmentation: 2
Final evaluation on all classes (Exemplar mean)
	Best top1 validation accuracy: 0.425000
	Best top5 validation accuracy: 0.890000
augmentation: 2
Final evaluation on all classes (Theoretical mean)
	Best top1 validation accuracy: 0.422500
	Best top5 validation accuracy: 0.892500


In [ ]:
base_dir='breakhis_Mar21_full_dataset'
tf_networks['train_network'].load_model('%s/best_model_params_0.pkl'%base_dir,sess)
tf_networks['test_network'].load_model('%s/best_model_params_0.pkl'%base_dir,sess)
# with open('%s/theoretical_mean.pkl'%base_dir,'rb') as f:
#     theoretical_mean=pickle.load(f)
# with open('%s/exemplar_mean.pkl'%base_dir,'rb') as f:
#     exemplar_mean=pickle.load(f)
# with open('%s/class_ord.json'%base_dir,'r') as f:
#     class_ord=json.load(f)
plain_evaluation_tensors=dict(loss=tf_tensors['loss_test'],
                        class_loss=tf_tensors['class_loss_test'],
                        regularization_loss=tf_tensors['top1_accuracy_test'],
                        top1_accuracy=tf_tensors['top1_accuracy_test'],
                        top5_accuracy=tf_tensors['top5_accuracy_test'],
                        X=tf_tensors['X_test'],
                        Y=tf_tensors['Y_test'])    
test_eval_vals=test_accuracy_evaluation_plain(data_dict_total['X_test'],
                                               data_dict_total['Y_test'],
                                               hyper_params['test_batch_size'],
                                               plain_evaluation_tensors,sess,dataset='breakhis')
# feature_map_tensors=dict(X=tf_tensors['X_test'],feature_map=tf_tensors['feature_map_test'])
# exemplar_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
#                                        exemplar_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)    
# theoretical_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
#                                        theoretical_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
print(test_eval_vals['top1_accuracy'])
# print(exemplar_eval_vals['top1_accuracy'])
# print(theoretical_eval_vals['top1_accuracy'])

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'history.json')) as f:
    history_d=json.load(f)
plt.plot(range(1,len(history_d[0]['loss_train'])+1),history_d[0]['loss_train'],label='loss train')
plt.plot(range(1,len(history_d[0]['loss_test'])+1),history_d[0]['loss_test'],label='loss test')
plt.legend()

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'history.json')) as f:
    history_d=json.load(f)
plt.plot(range(1,len(history_d[0]['top1_accuracy_train'])+1),history_d[0]['top1_accuracy_train'],label='top1_accuracy train')
plt.plot(range(1,len(history_d[0]['top1_accuracy_test'])+1),history_d[0]['top1_accuracy_test'],label='top1_accuracy test')
plt.legend()

In [ ]:
it=iterate_minibatches_breakhis(data_dict_total['X_train'],data_dict_total['Y_train'],10,augment=True,shuffle=True)

In [ ]:
plt.imshow(X_b[0])
plt.gcf().set_size_inches((20,12))