In [2]:
import os
os.environ['CUDA_VISIBLE_DEVICES']="0"
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from collections import defaultdict
from itertools import combinations
from itertools import chain
from collections import namedtuple
import pickle
import tensorflow as tf
import tflearn
import matplotlib.pyplot as plt
import os.path
import shutil
import inspect
from nn_lib import *
from train_procedures import *
from train_utils import *
from breakhis_utils import *
import matplotlib.pyplot as plt
import json
from pprint import pprint
from copy import copy
from sklearn.metrics import confusion_matrix
import seaborn as sns
np.random.seed(1997)
%load_ext autoreload
%autoreload 2

In [3]:
data_set_total=load_breakhis_data(400)

7908

In [4]:
cifar100_total=load_cifar100_data(normalize=False)

In [16]:
hyper_params={'beta':1e-5,
              'initial_lr':0.1,
              'train_batch_size':64,
              'test_batch_size':64,
              'lr_reduction_rate':10,
              'lr_reduction_epoch':[15,25,35],
              'use_fixedsize_exemplar':True,
              'exemplar_set_size':1600,
              'final_train_epochs':5,
              'se':True,
              'primary_exemplar':'icarl_exemplar',
              'train_method':'train_distillation',
              'sample_weight':1e-5,
              'shuffle_class_ord':False,
              'optimizer':'momentum',
              'ewc_lambda':0,
              'loss_function':'sigmoid_cross_entropy_with_logits'}
fixed_params={'dataset':'breakhis',
              'net_type':'ResNet18',
              'random_seed':1997,
              'total_num_classes':8,
              'base_dir':'./breakhis_temp2',
              'class_batch_size':2,
              'use_theoretical_mean':True}

In [17]:
data_dict_total=dict(X_train=data_set_total['X_train'],
                     Y_train=data_set_total['fine_labels_train'],
                     X_test=data_set_total['X_test'],
                     Y_test=data_set_total['fine_labels_test'])

In [18]:
# data_dict_total=dict(X_train=cifar100_total['X_train'],
#                      Y_train=cifar100_total['Y_train'],
#                      X_test=cifar100_total['X_test'],
#                      Y_test=cifar100_total['Y_test'])

In [19]:
tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)

log_prob
log_prob
log_prob


In [20]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=1.0)
sess=tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

In [ ]:
fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict_total,sess,resume=False,
        save_session=False,save_session_freq=1,save_params=True,evaluation_metric='top1_accuracy',save_history=True,
        num_epochs=45,num_iterations=4,verbose=2,print_freq=1,pretrain_evaluation=0,override_warning=True)

{'base_dir': './breakhis_temp2',
 'class_batch_size': 2,
 'dataset': 'breakhis',
 'net_type': 'ResNet18',
 'random_seed': 1997,
 'total_num_classes': 8,
 'use_theoretical_mean': True}
{'beta': 1e-05,
 'ewc_lambda': 0,
 'exemplar_set_size': 1600,
 'final_train_epochs': 5,
 'initial_lr': 0.1,
 'loss_function': 'sigmoid_cross_entropy_with_logits',
 'lr_reduction_epoch': [15, 25, 35],
 'lr_reduction_rate': 10,
 'optimizer': 'momentum',
 'primary_exemplar': 'icarl_exemplar',
 'sample_weight': 1e-05,
 'se': True,
 'shuffle_class_ord': False,
 'test_batch_size': 64,
 'train_batch_size': 64,
 'train_method': 'train_distillation',
 'use_fixedsize_exemplar': True}
data_dict_current: 5074
Counter({0: 2537, 1: 2537})
data_dict_current_weight:
Counter({1: 5074})
data_dict_total: 400
Counter({0: 50, 1: 50, 2: 50, 3: 50, 4: 50, 5: 50, 6: 50, 7: 50})
===========Iteration 1=============
Using classes [0, 1]
Epoch 1
	Train loss: 0.136338
	Train class loss: 0.079451
	Train reg loss: 0.056887
	Validation 

epoch 18, global step 18, time 95.071333
Epoch 19
	Train loss: 0.055854
	Train class loss: 0.000048
	Train reg loss: 0.055806
	Validation loss: 0.055808
	Validation class loss: 0.000006
	Validation reg loss: 0.055801
	Top1 train accuracy: 1.000000
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 1.000000
	Top5 validation accuracy: 1.000000
[[50  0]
 [ 0 50]]
network nan test after epoch
mbi=3635646720
epoch 19, global step 19, time 95.295624
Epoch 20
	Train loss: 0.055830
	Train class loss: 0.000033
	Train reg loss: 0.055797
	Validation loss: 0.055799
	Validation class loss: 0.000007
	Validation reg loss: 0.055792
	Top1 train accuracy: 1.000000
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 1.000000
	Top5 validation accuracy: 1.000000
[[50  0]
 [ 0 50]]
network nan test after epoch
mbi=3635646720
epoch 20, global step 20, time 93.590222
Epoch 21
	Train loss: 0.055821
	Train class loss: 0.000033
	Train reg loss: 0.055788
	Validation loss: 0.055790
	Validation class l

epoch 38, global step 38, time 91.628660
Epoch 39
	Train loss: 0.055770
	Train class loss: 0.000031
	Train reg loss: 0.055739
	Validation loss: 0.055745
	Validation class loss: 0.000006
	Validation reg loss: 0.055739
	Top1 train accuracy: 1.000000
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 1.000000
	Top5 validation accuracy: 1.000000
[[50  0]
 [ 0 50]]
network nan test after epoch
mbi=3635646720
epoch 39, global step 39, time 91.427020
Epoch 40
	Train loss: 0.055775
	Train class loss: 0.000036
	Train reg loss: 0.055739
	Validation loss: 0.055746
	Validation class loss: 0.000007
	Validation reg loss: 0.055739
	Top1 train accuracy: 1.000000
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 1.000000
	Top5 validation accuracy: 1.000000
[[50  0]
 [ 0 50]]
network nan test after epoch
mbi=3635646720
epoch 40, global step 40, time 90.803097
Epoch 41
	Train loss: 0.055766
	Train class loss: 0.000026
	Train reg loss: 0.055739
	Validation loss: 0.055745
	Validation class l

/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Epoch 1
	Train loss: 0.283261
	Train class loss: 0.226832
	Train reg loss: 0.056428
	Validation loss: 0.665962
	Validation class loss: 0.609555
	Validation reg loss: 0.056406
	Top1 train accuracy: 0.334435
	Top5 train accuracy: 0.982121
	Top1 validation accuracy: 0.240000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0]
 [ 0  0  0  0]
 [10 19 21  0]
 [15 26  6  3]]
network nan test after epoch
mbi=3635646720
epoch 1, global step 46, time 135.385903
saving model parameters...
Epoch 2
	Train loss: 0.144147
	Train class loss: 0.087770
	Train reg loss: 0.056377
	Validation loss: 1.498128
	Validation class loss: 1.441781
	Validation reg loss: 0.056346
	Top1 train accuracy: 0.387470
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.080000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0]
 [ 0  0  0  0]
 [21 19  4  6]
 [44  2  0  4]]
network nan test after epoch
mbi=3635646720
epoch 2, global step 47, time 135.676253
Epoch 3
	Train loss: 0.116579
	Train class loss: 0.060263
	Trai

/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Epoch 4
	Train loss: 0.109907
	Train class loss: 0.053652
	Train reg loss: 0.056255
	Validation loss: 1.475477
	Validation class loss: 1.419251
	Validation reg loss: 0.056226
	Top1 train accuracy: 0.558594
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.140000
	Top5 validation accuracy: 0.980000
[[ 0  0  0  0]
 [ 0  0  0  0]
 [20 16 14  0]
 [47  3  0  0]]
network nan test after epoch
mbi=3635646720
epoch 4, global step 49, time 135.294084
Epoch 5
	Train loss: 0.096338
	Train class loss: 0.040144
	Train reg loss: 0.056193
	Validation loss: 0.774547
	Validation class loss: 0.718392
	Validation reg loss: 0.056156
	Top1 train accuracy: 0.633564
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.370000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0]
 [ 0  0  0  0]
 [12 23 15  0]
 [ 9 19  0 22]]
network nan test after epoch
mbi=3635646720
epoch 5, global step 50, time 136.282016
Epoch 6
	Train loss: 0.088201
	Train class loss: 0.032083
	Train reg loss: 0.056118
	Valid

Epoch 22
	Train loss: 0.075033
	Train class loss: 0.019935
	Train reg loss: 0.055099
	Validation loss: 0.813985
	Validation class loss: 0.758892
	Validation reg loss: 0.055093
	Top1 train accuracy: 0.921575
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.970000
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 3 47  0]
 [ 0  0 50]]
network nan test after epoch
mbi=3635646720
epoch 22, global step 67, time 137.901313
saving model parameters...
Epoch 23
	Train loss: 0.075044
	Train class loss: 0.019956
	Train reg loss: 0.055088
	Validation loss: 0.839368
	Validation class loss: 0.784287
	Validation reg loss: 0.055082
	Top1 train accuracy: 0.917067
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.950000
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 5 45  0]
 [ 0  0 50]]
network nan test after epoch
mbi=3635646720
epoch 23, global step 68, time 137.889271
Epoch 24
	Train loss: 0.075160
	Train class loss: 0.020084
	Train reg loss: 0.055076
	Validation loss: 0.86

epoch 40, global step 85, time 137.200172
Epoch 41
	Train loss: 0.074893
	Train class loss: 0.019845
	Train reg loss: 0.055048
	Validation loss: 0.865905
	Validation class loss: 0.810857
	Validation reg loss: 0.055048
	Top1 train accuracy: 0.916767
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.920000
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 8 42  0]
 [ 0  0 50]]
network nan test after epoch
mbi=3635646720
epoch 41, global step 86, time 138.182414
Epoch 42
	Train loss: 0.074932
	Train class loss: 0.019884
	Train reg loss: 0.055048
	Validation loss: 0.849018
	Validation class loss: 0.793970
	Validation reg loss: 0.055048
	Top1 train accuracy: 0.913311
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.930000
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 7 43  0]
 [ 0  0 50]]
network nan test after epoch
mbi=3635646720
epoch 42, global step 87, time 137.948185
Epoch 43
	Train loss: 0.075132
	Train class loss: 0.020084
	Train reg loss: 0.055048
	Valida

epoch 1, global step 91, time 131.157094
saving model parameters...
Epoch 2
	Train loss: 0.232055
	Train class loss: 0.177015
	Train reg loss: 0.055039
	Validation loss: 1.322102
	Validation class loss: 1.267093
	Validation reg loss: 0.055009
	Top1 train accuracy: 0.330980
	Top5 train accuracy: 0.998798
	Top1 validation accuracy: 0.270000
	Top5 validation accuracy: 0.940000
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [22  0  1 27  0]
 [35  1  3 11  0]]
network nan test after epoch
mbi=3635646720
epoch 2, global step 92, time 128.802727
saving model parameters...
Epoch 3
	Train loss: 0.203355
	Train class loss: 0.148371
	Train reg loss: 0.054984
	Validation loss: 0.849086
	Validation class loss: 0.794128
	Validation reg loss: 0.054959
	Top1 train accuracy: 0.374850
	Top5 train accuracy: 0.998948
	Top1 validation accuracy: 0.540000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 2  8  0 40  0]
 [ 1 32  1  2 14]]
network nan test aft

epoch 18, global step 108, time 136.400779
Epoch 23
	Train loss: 0.165651
	Train class loss: 0.112873
	Train reg loss: 0.052778
	Validation loss: 1.081407
	Validation class loss: 1.028634
	Validation reg loss: 0.052773
	Top1 train accuracy: 0.850060
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.960000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 1  0 49  0]
 [ 2  1  0 47]]
network nan test after epoch
mbi=3635646720
epoch 23, global step 158, time 126.743282
Epoch 24
	Train loss: 0.165568
	Train class loss: 0.112800
	Train reg loss: 0.052767
	Validation loss: 1.055450
	Validation class loss: 1.002688
	Validation reg loss: 0.052762
	Top1 train accuracy: 0.851563
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.970000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 1  0 49  0]
 [ 1  1  0 48]]
network nan test after epoch
mbi=3635646720
epoch 24, global step 159, time 127.429737
Epoch 25
	Train loss: 0.165735
	Train cla

In [ ]:
base_dir='breakhis_Mar21_full_dataset'
tf_networks['train_network'].load_model('%s/best_model_params_0.pkl'%base_dir,sess)
tf_networks['test_network'].load_model('%s/best_model_params_0.pkl'%base_dir,sess)
# with open('%s/theoretical_mean.pkl'%base_dir,'rb') as f:
#     theoretical_mean=pickle.load(f)
# with open('%s/exemplar_mean.pkl'%base_dir,'rb') as f:
#     exemplar_mean=pickle.load(f)
# with open('%s/class_ord.json'%base_dir,'r') as f:
#     class_ord=json.load(f)
plain_evaluation_tensors=dict(loss=tf_tensors['loss_test'],
                        class_loss=tf_tensors['class_loss_test'],
                        regularization_loss=tf_tensors['top1_accuracy_test'],
                        top1_accuracy=tf_tensors['top1_accuracy_test'],
                        top5_accuracy=tf_tensors['top5_accuracy_test'],
                        X=tf_tensors['X_test'],
                        Y=tf_tensors['Y_test'])    
test_eval_vals=test_accuracy_evaluation_plain(data_dict_total['X_test'],
                                               data_dict_total['Y_test'],
                                               hyper_params['test_batch_size'],
                                               plain_evaluation_tensors,sess,dataset='breakhis')
# feature_map_tensors=dict(X=tf_tensors['X_test'],feature_map=tf_tensors['feature_map_test'])
# exemplar_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
#                                        exemplar_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)    
# theoretical_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
#                                        theoretical_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
print(test_eval_vals['top1_accuracy'])
# print(exemplar_eval_vals['top1_accuracy'])
# print(theoretical_eval_vals['top1_accuracy'])

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'history.json')) as f:
    history_d=json.load(f)
plt.plot(range(1,len(history_d[0]['loss_train'])+1),history_d[0]['loss_train'],label='loss train')
plt.plot(range(1,len(history_d[0]['loss_test'])+1),history_d[0]['loss_test'],label='loss test')
plt.legend()

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'history.json')) as f:
    history_d=json.load(f)
plt.plot(range(1,len(history_d[0]['top1_accuracy_train'])+1),history_d[0]['top1_accuracy_train'],label='top1_accuracy train')
plt.plot(range(1,len(history_d[0]['top1_accuracy_test'])+1),history_d[0]['top1_accuracy_test'],label='top1_accuracy test')
plt.legend()

In [ ]:
it=iterate_minibatches_breakhis(data_dict_total['X_train'],data_dict_total['Y_train'],10,augment=True,shuffle=True)

In [ ]:
plt.imshow(X_b[0])
plt.gcf().set_size_inches((20,12))