In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES']="0"
import pandas as pd
import numpy as np
from collections import defaultdict
from itertools import combinations
from itertools import chain
from collections import namedtuple
import pickle
import tensorflow as tf
import tflearn
import matplotlib.pyplot as plt
import os.path
import shutil
import inspect
import matplotlib.pyplot as plt
import json
from pprint import pprint
from copy import copy
from tflearn.datasets import cifar10
from nn_lib import *
from train_utils import *
from train_procedures import *
np.random.seed(1997)
# %load_ext autoreload
# %autoreload 2
ALGORITHM=sys.argv[1]
BASE_DIR=sys.argv[2]
if ALGORITHM=='full_data':
    CLASS_BATCH_SIZE=int(sys.argv[3])

hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)


In [2]:
data_dict={}
(data_dict['X_train'],data_dict['Y_train']),(data_dict['X_test'],data_dict['Y_test'])=cifar10.load_data('./')
data_dict['Y_test']=np.array(data_dict['Y_test'])

In [3]:
# for testing purposes
ALGORITHM="SupportNet"

In [4]:
#non-incremental settings
if ALGORITHM == 'ft':
    hyper_params={'beta':1e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar10',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':10,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
#icarl settings
elif ALGORITHM == 'icarl':
    hyper_params={'beta':1e-3,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':5,
                  'se':True,
                  'primary_exemplars':'icarl_exemplars',
                  'train_method':'train_distillation',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar10',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':10,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
#SupportNet settings
elif ALGORITHM == 'SupportNet':
    hyper_params={'beta':1e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':5,
                  'se':True,
                  'primary_exemplars':'svm_exemplars',
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':1e-2,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar10',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':10,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
#ewc settings
elif ALGORITHM == 'ewc':
    hyper_params={'beta':2e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':1e-2,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar10',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':10,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
elif ALGORITHM == 'full_data':
    hyper_params={'beta':1e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar10',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':10,
                  'base_dir':BASE_DIR,
                  'class_batch_size':CLASS_BATCH_SIZE,
                  'use_theoretical_mean':True}
else:
    assert False

In [5]:
tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)

Use ResNet32


/home/liz0f/SupportNet/train_procedures.py:50: UserWarning: when use ewc, loss_function should be softmax
  warnings.warn('when use ewc, loss_function should be softmax')


Use ResNet32
Use ResNet32


In [6]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.8)
sess=tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

In [ ]:
if ALGORITHM=='full_data':
    fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
            save_params=True,evaluation_metric='top1_accuracy',save_history=True,
            num_epochs=70,num_iterations=1,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=False)
else:
    fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
            save_params=True,evaluation_metric='top1_accuracy',save_history=True,
            num_epochs=70,num_iterations=5,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=False)

{'base_dir': './Aug25-cifar10-icarl-debug2',
 'class_batch_size': 2,
 'dataset': 'cifar10',
 'net_type': 'ResNet32',
 'random_seed': 1997,
 'total_num_classes': 10,
 'use_theoretical_mean': True}
{'beta': 0.0002,
 'ewc_lambda': 0,
 'exemplars_set_size': 2000,
 'final_train_epochs': 5,
 'initial_lr': 0.1,
 'loss_function': 'sigmoid_cross_entropy_with_logits',
 'lr_reduction_epoch': [49, 63],
 'lr_reduction_rate': 10,
 'optimizer': 'momentum',
 'primary_exemplars': 'icarl_exemplars',
 'sample_weight': 0,
 'se': True,
 'shuffle_class_ord': False,
 'test_batch_size': 64,
 'train_batch_size': 64,
 'train_method': 'train_distillation',
 'use_fixedsize_exemplars': True}
./Aug25-cifar10-icarl-debug2 already exists, override?y
Y_train class info:
Counter({1: 5000, 0: 5000})
Y_test class info:
Counter({0: 1000, 1: 1000})
===========Iteration 1=============
Using classes [0, 1]


/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.361058
	Train class loss: 0.069459
	Train reg loss: 0.291599
	Validation loss: 0.361188
	Validation class loss: 0.069589
	Validation reg loss: 0.291599
	Top1 train accuracy: 0.392800
	Top5 train accuracy: 1.000000
	Top1 validation accuracy: 0.367500
	Top5 validation accuracy: 1.000000
[[118 865  17]
 [371 617  12]
 [  0   0   0]]
Epoch 1
	Train loss: 0.375489
	Train class loss: 0.090525
	Train reg loss: 0.284964
	Validation loss: 0.282078
	Validation class loss: 0.004748
	Validation reg loss: 0.277330
	Top1 train accuracy: 0.810600
	Top5 train accuracy: 0.997800
	Top1 validation accuracy: 0.904000
	Top5 validation accuracy: 1.000000
[[876 124]
 [ 68 932]]
mbi=275436032
time= 29.415866
saving model parameters...
Epoch 2
	Train loss: 0.321500
	Train class loss: 0.052528
	Train reg loss: 0.268971
	Validation loss: 0.266524
	Validation class loss: 0.004974
	Validation reg loss: 0.261550
	Top1 train accuracy: 0.891700
	Top5 train

Epoch 22
	Train loss: 0.097737
	Train class loss: 0.010740
	Train reg loss: 0.086996
	Validation loss: 0.086250
	Validation class loss: 0.001396
	Validation reg loss: 0.084855
	Top1 train accuracy: 0.978500
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.976500
	Top5 validation accuracy: 1.000000
[[990  10]
 [ 37 963]]
mbi=275436032
time= 26.150210
Epoch 23
	Train loss: 0.093870
	Train class loss: 0.011307
	Train reg loss: 0.082563
	Validation loss: 0.081789
	Validation class loss: 0.001228
	Validation reg loss: 0.080562
	Top1 train accuracy: 0.978500
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.980500
	Top5 validation accuracy: 1.000000
[[982  18]
 [ 21 979]]
mbi=275436032
time= 26.089044
Epoch 24
	Train loss: 0.089128
	Train class loss: 0.010694
	Train reg loss: 0.078433
	Validation loss: 0.077970
	Validation class loss: 0.001434
	Validation reg loss: 0.076536
	Top1 train accuracy: 0.978800
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.977500


Epoch 45
	Train loss: 0.040030
	Train class loss: 0.008278
	Train reg loss: 0.031752
	Validation loss: 0.032842
	Validation class loss: 0.001545
	Validation reg loss: 0.031298
	Top1 train accuracy: 0.984100
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.975000
	Top5 validation accuracy: 1.000000
[[956  44]
 [  6 994]]
mbi=275436032
time= 26.577914
Epoch 46
	Train loss: 0.040777
	Train class loss: 0.009960
	Train reg loss: 0.030817
	Validation loss: 0.031833
	Validation class loss: 0.001373
	Validation reg loss: 0.030460
	Top1 train accuracy: 0.979800
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.975500
	Top5 validation accuracy: 1.000000
[[991   9]
 [ 40 960]]
mbi=275436032
time= 26.556336
Epoch 47
	Train loss: 0.038119
	Train class loss: 0.008154
	Train reg loss: 0.029965
	Validation loss: 0.030548
	Validation class loss: 0.001010
	Validation reg loss: 0.029539
	Top1 train accuracy: 0.984800
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.984000


Epoch 67
	Train loss: 0.028493
	Train class loss: 0.002342
	Train reg loss: 0.026151
	Validation loss: 0.026771
	Validation class loss: 0.000584
	Validation reg loss: 0.026187
	Top1 train accuracy: 0.996200
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.992000
	Top5 validation accuracy: 1.000000
[[992   8]
 [  8 992]]
mbi=275436032
time= 26.798659
Epoch 68
	Train loss: 0.028146
	Train class loss: 0.002006
	Train reg loss: 0.026139
	Validation loss: 0.026774
	Validation class loss: 0.000599
	Validation reg loss: 0.026175
	Top1 train accuracy: 0.996600
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.991000
	Top5 validation accuracy: 1.000000
[[990  10]
 [  8 992]]
mbi=275436032
time= 26.642970
Epoch 69
	Train loss: 0.028406
	Train class loss: 0.002279
	Train reg loss: 0.026127
	Validation loss: 0.026751
	Validation class loss: 0.000588
	Validation reg loss: 0.026163
	Top1 train accuracy: 0.995600
	Top5 train accuracy: 0.998400
	Top1 validation accuracy: 0.992000


/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.133933
	Train class loss: 0.107782
	Train reg loss: 0.026151
	Validation loss: 0.155445
	Validation class loss: 0.129294
	Validation reg loss: 0.026151
	Top1 train accuracy: 0.166667
	Top5 train accuracy: 0.497417
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.415000
[[  0   0   0   0]
 [  0   0   0   0]
 [934  66   0   0]
 [861 139   0   0]]
Epoch 1
	Train loss: 0.222519
	Train class loss: 0.196792
	Train reg loss: 0.025727
	Validation loss: 0.063799
	Validation class loss: 0.037834
	Validation reg loss: 0.025965
	Top1 train accuracy: 0.197250
	Top5 train accuracy: 0.994583
	Top1 validation accuracy: 0.288500
	Top5 validation accuracy: 1.000000
[[  0   0   0   0]
 [  0   0   0   0]
 [627 129   0 244]
 [150 273   0 577]]
mbi=275436032
time= 38.165763
saving model parameters...
Epoch 2
	Train loss: 0.160693
	Train class loss: 0.134755
	Train reg loss: 0.025938
	Validation loss: 0.074592
	Validation class los

Epoch 20
	Train loss: 0.109560
	Train class loss: 0.080466
	Train reg loss: 0.029094
	Validation loss: 0.072515
	Validation class loss: 0.043321
	Validation reg loss: 0.029195
	Top1 train accuracy: 0.597833
	Top5 train accuracy: 0.997333
	Top1 validation accuracy: 0.384500
	Top5 validation accuracy: 1.000000
[[  0   0   0   0]
 [  0   0   0   0]
 [651  17 328   4]
 [476  50  33 441]]
mbi=275436032
time= 36.514426
Epoch 21
	Train loss: 0.108380
	Train class loss: 0.079198
	Train reg loss: 0.029182
	Validation loss: 0.079288
	Validation class loss: 0.050023
	Validation reg loss: 0.029265
	Top1 train accuracy: 0.592000
	Top5 train accuracy: 0.997333
	Top1 validation accuracy: 0.365500
	Top5 validation accuracy: 1.000000
[[  0   0   0   0]
 [  0   0   0   0]
 [761   5 218  16]
 [478   5   4 513]]
mbi=275436032
time= 36.519872
Epoch 22
	Train loss: 0.106853
	Train class loss: 0.077585
	Train reg loss: 0.029268
	Validation loss: 0.070844
	Validation class loss: 0.041463
	Validation reg loss:

Epoch 40
	Train loss: 0.103208
	Train class loss: 0.071876
	Train reg loss: 0.031332
	Validation loss: 0.074820
	Validation class loss: 0.043427
	Validation reg loss: 0.031393
	Top1 train accuracy: 0.650750
	Top5 train accuracy: 0.997333
	Top1 validation accuracy: 0.575500
	Top5 validation accuracy: 1.000000
[[  0   0   0   0]
 [  0   0   0   0]
 [371   6 615   8]
 [399  21  44 536]]
mbi=275436032
time= 36.399432
Epoch 41
	Train loss: 0.102901
	Train class loss: 0.071500
	Train reg loss: 0.031401
	Validation loss: 0.069218
	Validation class loss: 0.037714
	Validation reg loss: 0.031504
	Top1 train accuracy: 0.662083
	Top5 train accuracy: 0.997333
	Top1 validation accuracy: 0.674500
	Top5 validation accuracy: 0.999500
[[  0   0   0   0]
 [  0   0   0   0]
 [339  29 574  58]
 [180  30  15 775]]
mbi=275436032
time= 36.398996
saving model parameters...
Epoch 42
	Train loss: 0.102814
	Train class loss: 0.071313
	Train reg loss: 0.031501
	Validation loss: 0.074079
	Validation class loss: 0.0

Epoch 60
	Train loss: 0.079249
	Train class loss: 0.048225
	Train reg loss: 0.031023
	Validation loss: 0.073930
	Validation class loss: 0.042882
	Validation reg loss: 0.031049
	Top1 train accuracy: 0.786083
	Top5 train accuracy: 0.997333
	Top1 validation accuracy: 0.722500
	Top5 validation accuracy: 0.999500
[[  0   0   0   0]
 [  0   0   0   0]
 [325   9 644  22]
 [177  11  11 801]]
mbi=275436032
time= 36.508239
Epoch 61
	Train loss: 0.078058
	Train class loss: 0.047148
	Train reg loss: 0.030910
	Validation loss: 0.074759
	Validation class loss: 0.043824
	Validation reg loss: 0.030936
	Top1 train accuracy: 0.793833
	Top5 train accuracy: 0.997333
	Top1 validation accuracy: 0.706500
	Top5 validation accuracy: 0.999500
[[  0   0   0   0]
 [  0   0   0   0]
 [308   8 669  15]
 [221  16  19 744]]
mbi=275436032
time= 36.549693
Epoch 62
	Train loss: 0.076736
	Train class loss: 0.045940
	Train reg loss: 0.030796
	Validation loss: 0.075684
	Validation class loss: 0.044866
	Validation reg loss:

Y_train class info:
Counter({4: 5000, 5: 5000, 0: 500, 1: 500, 2: 500, 3: 500})
Y_test class info:
Counter({5: 1000, 4: 1000})
===========Iteration 3=============
Using classes [4, 5]
Class batch pretrain evaluation (plain method)
	Train loss: 0.168629
	Train class loss: 0.138003
	Train reg loss: 0.030626
	Validation loss: 0.191966
	Validation class loss: 0.161340
	Validation reg loss: 0.030626
	Top1 train accuracy: 0.148500
	Top5 train accuracy: 0.333167
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.179500
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [596  19 185 200   0   0]
 [270  23  73 634   0   0]]
Epoch 1
	Train loss: 0.274336
	Train class loss: 0.244348
	Train reg loss: 0.029987
	Validation loss: 0.101993
	Validation class loss: 0.072018
	Validation reg loss: 0.029976
	Top1 train accuracy: 0.127500
	Top5 train accuracy: 0.978167
	Top1 validation accuracy: 0.036500
	Top5 validation accuracy: 0.996

Epoch 16
	Train loss: 0.187912
	Train class loss: 0.153678
	Train reg loss: 0.034234
	Validation loss: 0.092862
	Validation class loss: 0.058422
	Validation reg loss: 0.034439
	Top1 train accuracy: 0.546500
	Top5 train accuracy: 0.992250
	Top1 validation accuracy: 0.481000
	Top5 validation accuracy: 0.985500
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [583   7  43  50 304  13]
 [196   3   9 133   1 658]]
mbi=275436032
time= 36.496739
Epoch 17
	Train loss: 0.186139
	Train class loss: 0.151690
	Train reg loss: 0.034449
	Validation loss: 0.087194
	Validation class loss: 0.052545
	Validation reg loss: 0.034649
	Top1 train accuracy: 0.550333
	Top5 train accuracy: 0.990917
	Top1 validation accuracy: 0.568000
	Top5 validation accuracy: 0.985000
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [283  22 139  23 528   5]
 [163  30  60 132   7 608]]
mbi=275436032
time= 36.5

Epoch 33
	Train loss: 0.181285
	Train class loss: 0.144445
	Train reg loss: 0.036840
	Validation loss: 0.115154
	Validation class loss: 0.078152
	Validation reg loss: 0.037001
	Top1 train accuracy: 0.611000
	Top5 train accuracy: 0.992583
	Top1 validation accuracy: 0.503000
	Top5 validation accuracy: 0.989500
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [282   2  10 121 579   6]
 [ 71   2   4 484  12 427]]
mbi=275436032
time= 37.177715
Epoch 34
	Train loss: 0.180411
	Train class loss: 0.143472
	Train reg loss: 0.036939
	Validation loss: 0.101486
	Validation class loss: 0.064398
	Validation reg loss: 0.037088
	Top1 train accuracy: 0.629333
	Top5 train accuracy: 0.992500
	Top1 validation accuracy: 0.660500
	Top5 validation accuracy: 0.973000
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [ 71   6   9  26 886   2]
 [230  19  31 249  36 435]]
mbi=275436032
time= 37.1

lr reduced to 0.010000
Epoch 50
	Train loss: 0.165236
	Train class loss: 0.126991
	Train reg loss: 0.038245
	Validation loss: 0.102672
	Validation class loss: 0.064394
	Validation reg loss: 0.038278
	Top1 train accuracy: 0.666583
	Top5 train accuracy: 0.995417
	Top1 validation accuracy: 0.667500
	Top5 validation accuracy: 0.990500
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [229   4  30  41 691   5]
 [143   2  12 192   7 644]]
mbi=275436032
time= 37.109539
Epoch 51
	Train loss: 0.158619
	Train class loss: 0.120512
	Train reg loss: 0.038107
	Validation loss: 0.104243
	Validation class loss: 0.066112
	Validation reg loss: 0.038132
	Top1 train accuracy: 0.683417
	Top5 train accuracy: 0.995750
	Top1 validation accuracy: 0.709000
	Top5 validation accuracy: 0.988500
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [188   3  14  46 742   7]
 [135   1  15 167   6 676]]
m

Epoch 67
	Train loss: 0.145048
	Train class loss: 0.108973
	Train reg loss: 0.036075
	Validation loss: 0.106688
	Validation class loss: 0.070525
	Validation reg loss: 0.036163
	Top1 train accuracy: 0.770250
	Top5 train accuracy: 0.996833
	Top1 validation accuracy: 0.733000
	Top5 validation accuracy: 0.987000
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [153   4  25  49 758  11]
 [109   1  11 163   8 708]]
mbi=275436032
time= 37.247970
Epoch 68
	Train loss: 0.144755
	Train class loss: 0.108697
	Train reg loss: 0.036058
	Validation loss: 0.107236
	Validation class loss: 0.071089
	Validation reg loss: 0.036147
	Top1 train accuracy: 0.775583
	Top5 train accuracy: 0.996917
	Top1 validation accuracy: 0.733500
	Top5 validation accuracy: 0.986000
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [155   4  22  52 757  10]
 [100   1   9 173   7 710]]
mbi=275436032
time= 37.3

Y_train class info:
Counter({6: 5000, 7: 5000, 0: 333, 1: 333, 2: 333, 3: 333, 4: 333, 5: 333})
Y_test class info:
Counter({6: 1000, 7: 1000})
===========Iteration 4=============
Using classes [6, 7]
Class batch pretrain evaluation (plain method)
	Train loss: 0.179632
	Train class loss: 0.143522
	Train reg loss: 0.036110
	Validation loss: 0.199936
	Validation class loss: 0.163826
	Validation reg loss: 0.036110
	Top1 train accuracy: 0.132355
	Top5 train accuracy: 0.166611
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [311  60 127 260 186  56   0   0]
 [454   9  42 121 257 117   0   0]]
Epoch 1
	Train loss: 0.345833
	Train class loss: 0.309974
	Train reg loss: 0.035859
	Validation loss: 0.105080
	Validation class loss: 0.068678
	Validation reg loss: 0.036

Epoch 13
	Train loss: 0.274537
	Train class loss: 0.236720
	Train reg loss: 0.037817
	Validation loss: 0.102286
	Validation class loss: 0.064342
	Validation reg loss: 0.037945
	Top1 train accuracy: 0.711119
	Top5 train accuracy: 0.987831
	Top1 validation accuracy: 0.762500
	Top5 validation accuracy: 0.985000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [144   7  13  70  42   4 715   5]
 [123   2   4  26   9  26   0 810]]
mbi=275436032
time= 36.227823
saving model parameters...
Epoch 14
	Train loss: 0.273308
	Train class loss: 0.235496
	Train reg loss: 0.037812
	Validation loss: 0.117668
	Validation class loss: 0.079736
	Validation reg loss: 0.037932
	Top1 train accuracy: 0.715869
	Top5 train accuracy: 0.987831
	Top1 validation accuracy: 0.626500
	Top5 validation accuracy: 0.959500
[[  0   0   0   0   0   0   0]
 [  0   0  

Epoch 27
	Train loss: 0.269649
	Train class loss: 0.231264
	Train reg loss: 0.038385
	Validation loss: 0.111379
	Validation class loss: 0.072870
	Validation reg loss: 0.038509
	Top1 train accuracy: 0.759377
	Top5 train accuracy: 0.990415
	Top1 validation accuracy: 0.598500
	Top5 validation accuracy: 0.978000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [149   6   5 121  68   1 650   0]
 [216   4   1  72 155   5   0 547]]
mbi=275436032
time= 36.476855
Epoch 28
	Train loss: 0.270707
	Train class loss: 0.232325
	Train reg loss: 0.038382
	Validation loss: 0.105366
	Validation class loss: 0.066844
	Validation reg loss: 0.038522
	Top1 train accuracy: 0.757043
	Top5 train accuracy: 0.989582
	Top1 validation accuracy: 0.860000
	Top5 validation accuracy: 0.993000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]

Epoch 41
	Train loss: 0.268908
	Train class loss: 0.230228
	Train reg loss: 0.038680
	Validation loss: 0.092753
	Validation class loss: 0.054017
	Validation reg loss: 0.038736
	Top1 train accuracy: 0.776046
	Top5 train accuracy: 0.990998
	Top1 validation accuracy: 0.899500
	Top5 validation accuracy: 0.992000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [ 47   1   7  14   1   1 928   1]
 [ 73   4  12  15  16   6   3 871]]
mbi=275436032
time= 36.497852
saving model parameters...
Epoch 42
	Train loss: 0.266190
	Train class loss: 0.227598
	Train reg loss: 0.038591
	Validation loss: 0.116055
	Validation class loss: 0.077387
	Validation reg loss: 0.038668
	Top1 train accuracy: 0.774212
	Top5 train accuracy: 0.992499
	Top1 validation accuracy: 0.675500
	Top5 validation accuracy: 0.954500
[[  0   0   0   0   0   0   0]
 [  0   0  

Epoch 55
	Train loss: 0.241648
	Train class loss: 0.203578
	Train reg loss: 0.038070
	Validation loss: 0.109186
	Validation class loss: 0.071107
	Validation reg loss: 0.038079
	Top1 train accuracy: 0.820887
	Top5 train accuracy: 0.996249
	Top1 validation accuracy: 0.837500
	Top5 validation accuracy: 0.992000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [ 52   0  10  37  15   8 876   2]
 [ 98   4   6  21  50  22   0 799]]
mbi=275436032
time= 36.546902
Epoch 56
	Train loss: 0.241059
	Train class loss: 0.203155
	Train reg loss: 0.037904
	Validation loss: 0.107694
	Validation class loss: 0.069782
	Validation reg loss: 0.037911
	Top1 train accuracy: 0.827305
	Top5 train accuracy: 0.996083
	Top1 validation accuracy: 0.848500
	Top5 validation accuracy: 0.990000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]

Epoch 69
	Train loss: 0.233477
	Train class loss: 0.196910
	Train reg loss: 0.036567
	Validation loss: 0.107623
	Validation class loss: 0.070973
	Validation reg loss: 0.036650
	Top1 train accuracy: 0.848225
	Top5 train accuracy: 0.997166
	Top1 validation accuracy: 0.858500
	Top5 validation accuracy: 0.990500
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [ 51   1  12  30  16   6 882   2]
 [ 78   3   5  19  47  13   0 835]]
mbi=275436032
time= 36.456569
Epoch 70
	Train loss: 0.234534
	Train class loss: 0.197984
	Train reg loss: 0.036550
	Validation loss: 0.107746
	Validation class loss: 0.071112
	Validation reg loss: 0.036633
	Top1 train accuracy: 0.847558
	Top5 train accuracy: 0.996333
	Top1 validation accuracy: 0.856500
	Top5 validation accuracy: 0.991000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]

Y_train class info:
Counter({9: 5000, 8: 5000, 0: 250, 1: 250, 2: 250, 3: 250, 4: 250, 5: 250, 6: 250, 7: 250})
Y_test class info:
Counter({8: 1000, 9: 1000})
===========Iteration 5=============
Using classes [8, 9]
Class batch pretrain evaluation (plain method)
	Train loss: 0.145743
	Train class loss: 0.109110
	Train reg loss: 0.036633
	Validation loss: 0.157662
	Validation class loss: 0.121029
	Validation reg loss: 0.036633
	Top1 train accuracy: 0.128833
	Top5 train accuracy: 0.166667
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [803 146   4  13   6   3  12  13   0   0]
 [218 701   3  23   5   5  10  35   0   0]]
Epoch

Epoch 12
	Train loss: 0.247238
	Train class loss: 0.212991
	Train reg loss: 0.034247
	Validation loss: 0.075815
	Validation class loss: 0.041521
	Validation reg loss: 0.034295
	Top1 train accuracy: 0.779583
	Top5 train accuracy: 0.987250
	Top1 validation accuracy: 0.875500
	Top5 validation accuracy: 0.987000
[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 95   8   3   1   0   1   4   4 879   5]
 [ 76  28   2   5   3   0   3   2   9 872]]
mbi=275436032
time= 36.216117
saving model parameters...
Epoch 13
	Train loss: 0.242435
	Train class loss: 0.208311
	Train reg loss: 0.034124
	Validation loss: 0.074269
	Validation class loss: 0.040120
	Validation reg loss: 0.034149
	Top1 train accuracy: 0.79

Epoch 24
	Train loss: 0.239999
	Train class loss: 0.206575
	Train reg loss: 0.033425
	Validation loss: 0.066931
	Validation class loss: 0.033404
	Validation reg loss: 0.033527
	Top1 train accuracy: 0.813917
	Top5 train accuracy: 0.989000
	Top1 validation accuracy: 0.929000
	Top5 validation accuracy: 0.983500
[[  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [ 50  25   0   1   4 880  40]
 [  9   9   1   0   0   3 978]]
mbi=275436032
time= 36.417164
saving model parameters...
Epoch 25
	Train loss: 0.238302
	Train class loss: 0.204868
	Train reg loss: 0.033434
	Validation loss: 0.073710
	Validation class loss: 0.040228
	Validation reg loss: 0.033482
	Top1 train accuracy: 0.821417
	Top5 train accuracy: 0.991750
	Top1 validation accuracy: 0.738000
	Top5 validation accuracy: 0.972000
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]


Epoch 37
	Train loss: 0.238822
	Train class loss: 0.205360
	Train reg loss: 0.033462
	Validation loss: 0.070610
	Validation class loss: 0.037060
	Validation reg loss: 0.033550
	Top1 train accuracy: 0.821917
	Top5 train accuracy: 0.989083
	Top1 validation accuracy: 0.899000
	Top5 validation accuracy: 0.987000
[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 45   4   1   1   0   1   1   0 946   1]
 [ 65  45   1   4   2   1   2   1  27 852]]
mbi=275436032
time= 36.497685
Epoch 38
	Train loss: 0.238281
	Train class loss: 0.204851
	Train reg loss: 0.033430
	Validation loss: 0.073539
	Validation class loss: 0.040009
	Validation reg loss: 0.033529
	Top1 train accuracy: 0.828583
	Top5 train accuracy: 

Epoch 49
	Train loss: 0.237947
	Train class loss: 0.204553
	Train reg loss: 0.033394
	Validation loss: 0.075545
	Validation class loss: 0.041986
	Validation reg loss: 0.033559
	Top1 train accuracy: 0.832500
	Top5 train accuracy: 0.991500
	Top1 validation accuracy: 0.585500
	Top5 validation accuracy: 0.925500
[[  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [232  32   5   0   1   3   1 724   2]
 [170 371   0   1   3   2   0   6 447]]
mbi=275436032
time= 36.541533
lr reduced to 0.010000
Epoch 50
	Train loss: 0.227534
	Train class loss: 0.194115
	Train reg loss: 0.033419
	Validation loss: 0.069090
	Validation class loss: 0.035634
	Validation reg loss: 0.033456
	Top1 train accuracy: 0.849333
	Top5 train accuracy: 0.993750
	Top1 validation accuracy: 0.899000
	Top5 valid

Epoch 60
	Train loss: 0.215177
	Train class loss: 0.182988
	Train reg loss: 0.032189
	Validation loss: 0.067790
	Validation class loss: 0.035573
	Validation reg loss: 0.032217
	Top1 train accuracy: 0.891417
	Top5 train accuracy: 0.996250
	Top1 validation accuracy: 0.906000
	Top5 validation accuracy: 0.992000
[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 65  15   1   0   1   1   2   3 908   4]
 [ 30  50   1   3   1   1   1   3   6 904]]
mbi=275436032
time= 36.480444
Epoch 61
	Train loss: 0.214920
	Train class loss: 0.182857
	Train reg loss: 0.032063
	Validation loss: 0.067934
	Validation class loss: 0.035851
	Validation reg loss: 0.032083
	Top1 train accuracy: 0.892583
	Top5 train accuracy: 

On iteration 5
Plain evaluation before retrain
	Best top1 validation accuracy: 0.905500
	Best top5 validation accuracy: 0.993000
	Best top1 cumul accuracy: 0.703800
	Best top5 cumul accuracy: 0.984900
	Best top1 ori accuracy: 0.920500
	Best top5 ori accuracy: 0.999000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       0.33      0.91      0.49      1000
          1       0.89      0.93      0.91      1000
          2       0.81      0.33      0.47      1000
          3       0.62      0.56      0.59      1000
          4       0.79      0.56      0.65      1000
          5       0.81      0.58      0.68      1000
          6       0.92      0.74      0.82      1000
          7       0.94      0.62      0.75      1000
          8       0.90      0.90      0.90      1000
          9       0.89      0.91      0.90      1000

avg / total       0.79      0.70      0.72     10000

1608 support_vectors for class 0
709 support_vectors for cla

In [16]:
data_dict_iterations=data_dict_each_iteration("Aug31-cifar10-SupportNet-full2",5,2,data_dict)

0
[0, 1]
1
[2, 3]
2
[4, 5]
3
[6, 7]
4
[8, 9]


In [17]:
eval_vals_lists_test=eval_vals_each_iteration("Aug31-cifar10-SupportNet-full2",5,2,tf_tensors,tf_networks,data_dict_iterations,"cifar10",sess)

0


/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liz0f/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liz0

1
2
3
4


In [18]:
for i in range(0,len(eval_vals_lists_test)):
    for j in range(0,len(eval_vals_lists_test)):
        print(eval_vals_lists_test[i][j]["top1_accuracy"],end=",")
    print()

0.9885,0.0,0.0,0.0,0.0,
0.898,0.9105,0.0,0.0,0.0,
0.8895,0.4795,0.932,0.0,0.0,
0.91,0.551,0.639,0.9655,0.0,
0.6395,0.5745,0.697,0.8205,0.972,
