In [22]:
import os
os.environ['CUDA_VISIBLE_DEVICES']="0"
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from collections import defaultdict
from itertools import combinations
from itertools import chain
from collections import namedtuple
import pickle
import tensorflow as tf
import tflearn
import matplotlib.pyplot as plt
import os.path
import shutil
import inspect
from nn_lib import *
from train_procedures import *
from train_utils import *
from cifar100_utils import *
import matplotlib.pyplot as plt
import json
from pprint import pprint
from copy import copy
from sklearn.metrics import confusion_matrix
import seaborn as sns
np.random.seed(1997)
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [23]:
data_dict=load_cifar100_data()

In [24]:
data_dict_total=data_dict

In [30]:
hyper_params={'beta':1e-5,
              'initial_lr':2,
              'train_batch_size':128,
              'test_batch_size':128,
              'lr_reduction_rate':5,
              'lr_reduction_epoch':[49,63],
              'use_fixedsize_exemplar':True,
              'exemplar_set_size':1000,
              'final_train_epochs':5,
              'se':True,
              'primary_exemplar':'svm_exemplar',
              'train_method':'train_with_sample_weight',
              'sample_weight':1,
              'shuffle_class_ord':False,
              'optimizer':'momentum',
              'ewc_lambda':1e-5,
              'loss_function':'softmax_cross_entropy_with_logits'}
fixed_params={'dataset':'cifar100',
              'net_type':'ResNet32',
              'random_seed':1997,
              'total_num_classes':10,
              'base_dir':'./cifar100_temp',
              'class_batch_size':10,
              'use_theoretical_mean':True}

In [31]:
tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)

In [32]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.4)
sess=tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

In [33]:
tf.global_variables_initializer().run()

In [34]:
fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
        save_session=False,save_session_freq=1,save_params=True,evaluation_metric='top1_accuracy',save_history=True,
        num_epochs=1,num_iterations=1,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=True)

{'base_dir': './cifar100_temp',
 'class_batch_size': 10,
 'dataset': 'cifar100',
 'net_type': 'ResNet32',
 'random_seed': 1997,
 'total_num_classes': 10,
 'use_theoretical_mean': True}
{'beta': 1e-05,
 'ewc_lambda': 1e-05,
 'exemplar_set_size': 1000,
 'final_train_epochs': 5,
 'initial_lr': 2,
 'loss_function': 'softmax_cross_entropy_with_logits',
 'lr_reduction_epoch': [49, 63],
 'lr_reduction_rate': 5,
 'optimizer': 'momentum',
 'primary_exemplar': 'svm_exemplar',
 'sample_weight': 1,
 'se': True,
 'shuffle_class_ord': False,
 'test_batch_size': 128,
 'train_batch_size': 128,
 'train_method': 'train_with_sample_weight',
 'use_fixedsize_exemplar': True}
./cifar100_temp already exists, override?y
===========Iteration 1=============
Using classes [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 2.695263
	Train class loss: 2.680719
	Train reg loss: 0.100000
	Validation loss: 2.705668
	Validation class loss: 2.691124
	Validation reg loss: 0.014544
	Top1 train accuracy: 0.100000
	Top5 train accuracy: 0.503800
	Top1 validation accuracy: 0.100000
	Top5 validation accuracy: 0.500000
[[100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]]
network nan test after epoch
Epoch 1
	Train loss: 0.232014
	Train class loss: 0.217259
	Train reg loss: 0.014755
	Validation loss: 2.980675
	Validation class loss: 2.965708
	Validation reg loss: 0.014967
	Top1 train accur

InvalidArgumentError: flat indices[127, :] = [127, 10] does not index into param (shape: [128,10]).
	 [[Node: GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](TopKV2_3/_1761, stack_1/_1763)]]
	 [[Node: GatherNd_1/_1765 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2329_GatherNd_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'GatherNd_1', defined at:
  File "/home/test_user/.conda/envs/tf/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "/home/test_user/.conda/envs/tf/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/home/test_user/.conda/envs/tf/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
    handle._run()
  File "/home/test_user/.conda/envs/tf/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-6626b12dcd72>", line 1, in <module>
    tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)
  File "/home/test_user/IL/myIL/train_procedures.py", line 138, in build_graph
    ranks_of_groud_truth_class_test=fixed_params['total_num_classes']-1-tf.gather_nd(ranks_of_indices_test,indexing_matrix_test)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in gather_nd
    name=name)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[127, :] = [127, 10] does not index into param (shape: [128,10]).
	 [[Node: GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](TopKV2_3/_1761, stack_1/_1763)]]
	 [[Node: GatherNd_1/_1765 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2329_GatherNd_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]


In [ ]:
train_idx=np.array([i in [45, 76, 92, 44, 34, 6, 9, 80, 20, 48] for i in data_dict['Y_train']])
test_idx=np.array([i in [45, 76, 92, 44, 34, 6, 9, 80, 20, 48] for i in data_dict['Y_test']])
X_train_c=data_dict['X_train'][train_idx]
Y_train_c=data_dict['Y_train'][train_idx]
X_test_c=data_dict['X_test'][test_idx]
Y_test_c=data_dict['Y_test'][test_idx]

In [ ]:
feature_map_tensors=dict(X=tf_tensors['X_test'],feature_map=tf_tensors['feature_map_test'])
feature_maps_train=test_get_feature_maps(X_train_c,128,feature_map_tensors,sess,dataset='cifar100')
feature_maps_test=test_get_feature_maps(X_test_c,128,feature_map_tensors,sess,dataset='cifar100')

In [ ]:
svm=svm_retrain_with_exemplars(exemplar,[45, 76, 92, 44, 34, 6, 9, 80, 20, 48],128,feature_map_tensors,sess,dataset='cifar100')

In [ ]:
pred_svm=test_prediction_svm(X_test_c,128,feature_map_tensors,svm,sess,dataset='cifar100')

In [ ]:
np.mean(pred_svm==Y_test_c)

In [ ]:
svm.classes_

In [ ]:
svm.support_

In [ ]:
svm.n_support_

In [ ]:
np.hstack([0,svm.n_support_]).cumsum()

In [ ]:
base_dir='cifar100_icarl_debug_Mar13_icarl_70epoch'
with open('%s/exemplar.pkl'%base_dir,'rb') as f:
    exemplar=pickle.load(f)
exemplars_up_to_now=exemplar.reshape(-1,32,32,3)
exemplars_up_to_now_label=np.tile(np.arange(100).reshape(100,1),[1,50]).reshape(-1,1).squeeze()
rand_idx=np.arange(5000)
np.random.shuffle(rand_idx)
exemplars_up_to_now=exemplars_up_to_now[rand_idx[:]]
exemplars_up_to_now_label=exemplars_up_to_now_label[rand_idx[:]]

# train_tensors=copy(tf_tensors)
# train_tensors['optimizer_train']=\
# tf.train.AdamOptimizer().\
# minimize(tf_tensors['loss_train'],var_list=[tf_networks['train_network'].tf_variables['fc/W'],
#                                             tf_networks['train_network'].tf_variables['fc/b']])
# tf.global_variables_initializer().run()

In [ ]:
tf_networks['train_network'].load_model('%s/best_model_params_9.pkl'%base_dir,sess)
tf_networks['test_network'].load_model('%s/best_model_params_9.pkl'%base_dir,sess)
with open('%s/theoretical_mean.pkl'%base_dir,'rb') as f:
    theoretical_mean=pickle.load(f)
with open('%s/exemplar_mean.pkl'%base_dir,'rb') as f:
    exemplar_mean=pickle.load(f)
with open('%s/class_ord.json'%base_dir,'r') as f:
    class_ord=json.load(f)
plain_evaluation_tensors=dict(loss=tf_tensors['loss_test'],
                        class_loss=tf_tensors['class_loss_test'],
                        regularization_loss=tf_tensors['top1_accuracy_test'],
                        top1_accuracy=tf_tensors['top1_accuracy_test'],
                        top5_accuracy=tf_tensors['top5_accuracy_test'],
                        X=tf_tensors['X_test'],
                        Y=tf_tensors['Y_test'])    
test_eval_vals=test_accuracy_evaluation_plain(data_dict_total['X_test'],
                                               data_dict_total['Y_test'],
                                               hyper_params['test_batch_size'],
                                               plain_evaluation_tensors,sess)
feature_map_tensors=dict(X=tf_tensors['X_test'],feature_map=tf_tensors['feature_map_test'])
exemplar_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
                                       exemplar_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)    
theoretical_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
                                       theoretical_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
print(test_eval_vals['top1_accuracy'])
print(exemplar_eval_vals['top1_accuracy'])
print(theoretical_eval_vals['top1_accuracy'])

In [ ]:
last_layer_retrain_with_exemplars(exemplar,class_ord,128,
                                      tf_tensors,tf_networks['train_network'],'%s/best_model_params_9.pkl'%base_dir,5,session=sess,dataset='cifar100')

In [ ]:
# for epoch in range(5):
#     print('Epoch %d'%(epoch+1))
#     train_eval_vals=train_plain(exemplars_up_to_now,exemplars_up_to_now_label,hyper_params['train_batch_size'],train_tensors,sess)
  
tf_networks['test_network'].set_model_params(tf_networks['train_network'].get_all_model_params())
plain_evaluation_tensors=dict(loss=tf_tensors['loss_test'],
                        class_loss=tf_tensors['class_loss_test'],
                        regularization_loss=tf_tensors['top1_accuracy_test'],
                        top1_accuracy=tf_tensors['top1_accuracy_test'],
                        top5_accuracy=tf_tensors['top5_accuracy_test'],
                        X=tf_tensors['X_test'],
                        Y=tf_tensors['Y_test'])    
test_eval_vals=test_accuracy_evaluation_plain(data_dict_total['X_test'],
                                               data_dict_total['Y_test'],
                                               hyper_params['test_batch_size'],
                                               plain_evaluation_tensors,sess)
feature_map_tensors=dict(X=tf_tensors['X_test'],feature_map=tf_tensors['feature_map_test'])
update_exemplar_mean(exemplar_mean,exemplar,fixed_params['class_batch_size'],hyper_params['test_batch_size'],9,class_ord,feature_map_tensors,sess)
exemplar_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
                                       exemplar_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)    
update_theoretical_mean(theoretical_mean,data_dict_total['X_train'],data_dict_total['Y_train'],fixed_params['class_batch_size'],hyper_params['test_batch_size'],9,class_ord,feature_map_tensors,sess)
theoretical_eval_vals=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],
                                       theoretical_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
print(test_eval_vals['top1_accuracy'])
print(exemplar_eval_vals['top1_accuracy'])
print(theoretical_eval_vals['top1_accuracy'])

In [ ]:
base_dir='cifar100_icarl_debug_Mar13_icarl_70epoch'

with open('%s/class_ord.json'%base_dir,'r') as f:
    class_ord=json.load(f)
row_order=np.array(class_ord)[:,np.newaxis]
col_order=np.array(class_ord)[np.newaxis,:]
#tf_networks['test_network'].load_model('%s/best_model_params_9.pkl'%base_dir,sess)
plain_evaluation_tensors=dict(loss=tf_tensors['loss_test'],
                        class_loss=tf_tensors['class_loss_test'],
                        regularization_loss=tf_tensors['top1_accuracy_test'],
                        top1_accuracy=tf_tensors['top1_accuracy_test'],
                        top5_accuracy=tf_tensors['top5_accuracy_test'],
                        X=tf_tensors['X_test'],
                        Y=tf_tensors['Y_test'],
                        fc=tf_networks['test_network'].tf_tensors['fc'])    
eval_plain=test_accuracy_evaluation_plain(data_dict_total['X_test'],
                                               data_dict_total['Y_test'],
                                               hyper_params['test_batch_size'],
                                               plain_evaluation_tensors,sess)
pred_plain=test_prediction_plain(data_dict_total['X_test'],hyper_params['test_batch_size'],plain_evaluation_tensors,sess)
mat1=confusion_matrix(data_dict_total['Y_test'],pred_plain)[row_order,col_order]
sns.heatmap(mat1,cmap='bwr',vmin=0,vmax=100)
plt.gcf().set_size_inches((15,12))

In [ ]:
np.mean(pred_ncm==data_dict_total['Y_test'])

In [ ]:
class_ord.index(45)

In [ ]:
params=pickle.load(open('%s/best_model_params_9.pkl'%base_dir,'rb'))

In [ ]:
params['conv_1/W']

In [ ]:
base_dir='cifar100_icarl_debug_Mar13_icarl_70epoch'
with open('%s/theoretical_mean.pkl'%base_dir,'rb') as f:
    theoretical_mean=pickle.load(f)
with open('%s/exemplar_mean.pkl'%base_dir,'rb') as f:
    exemplar_mean=pickle.load(f)
with open('%s/class_ord.json'%base_dir,'r') as f:
    class_ord=json.load(f)
row_order=np.array(class_ord)[:,np.newaxis]
col_order=np.array(class_ord)[np.newaxis,:]
tf_networks['test_network'].load_model('%s/best_model_params_9.pkl'%base_dir,sess)
evaluation_tensors={'X':tf_tensors['X_test'],'fc':tf_networks['test_network'].tf_tensors['fc']}
eval_ncm=test_accuracy_evaluation_ncm(data_dict_total['X_test'],data_dict_total['Y_test'],exemplar_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
pred_ncm=test_prediction_ncm(data_dict_total['X_test'],exemplar_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
mat1=confusion_matrix(data_dict_total['Y_test'],pred_ncm)[row_order,col_order]
sns.heatmap(mat1,cmap='bwr',vmin=0,vmax=100)
plt.gcf().set_size_inches((15,12))

In [ ]:
ravel_ord=mat1.ravel().argsort()
inter_class_batch_cumsum=0
for i in range(len(ravel_ord)-1,-1,-1):
    row,col=np.unravel_index(ravel_ord[i],mat1.shape)
    row_batch,col_batch=int(class_ord.index(row)/10),int(class_ord.index(col)/10)
    if row_batch!=col_batch:
        inter_class_batch_cumsum+=mat1[row,col]
    
    
        

In [ ]:
np.trace(mat1)/(np.sum(mat1)-np.trace(mat1))

In [ ]:
cifar100_icarl_debug_Mar13_icarl_70epoch
history1=json.load(open('cifar100_icarl_debug_Mar13_icarl_70epoch/history.json'))
history2=json.load(open('cifar100_icarl_debug_Mar14_plain_70epoch/history.json'))
history3=json.load(open('cifar100_icarl_debug_Mar15_sample_weight_70epoch/history.json'))
history4=json.load(open('cifar100_icarl_debug_Mar15_distillation_and_ground_truth_70epoch/history.json'))
history5=json.load(open('cifar100_icarl_debug_Mar16_sample_weight_exemplar_by_loss_70epoch/history.json'))
plt.plot(range(1,11),[history1[i]['best_top1_accuracy_exemplar_mean_cumul'] for i in range(10)],label='history1')
plt.plot(range(1,11),[history2[i]['best_top1_accuracy_exemplar_mean_cumul'] for i in range(10)],label='history2')
plt.plot(range(1,11),[history3[i]['best_top1_accuracy_exemplar_mean_cumul'] for i in range(10)],label='history3')
plt.plot(range(1,11),[history4[i]['best_top1_accuracy_exemplar_mean_cumul'] for i in range(10)],label='history4')
plt.plot(range(1,11),[history5[i]['best_top1_accuracy_exemplar_mean_cumul'] for i in range(10)],label='history5')
plt.ylim([0.3,1])
plt.legend()
plt.figure()
plt.plot(range(1,11),[history1[i]['best_top1_accuracy_exemplar_mean_test'] for i in range(10)],label='history1')
plt.plot(range(1,11),[history2[i]['best_top1_accuracy_exemplar_mean_test'] for i in range(10)],label='history2')
plt.plot(range(1,11),[history3[i]['best_top1_accuracy_exemplar_mean_test'] for i in range(10)],label='history3')
plt.plot(range(1,11),[history4[i]['best_top1_accuracy_exemplar_mean_test'] for i in range(10)],label='history4')
plt.plot(range(1,11),[history5[i]['best_top1_accuracy_exemplar_mean_test'] for i in range(10)],label='history5')
plt.ylim([0.3,1])
plt.legend()
plt.figure()
plt.plot(range(1,11),[history1[i]['best_top1_accuracy_exemplar_mean_ori'] for i in range(10)],label='history1')
plt.plot(range(1,11),[history2[i]['best_top1_accuracy_exemplar_mean_ori'] for i in range(10)],label='history2')
plt.plot(range(1,11),[history3[i]['best_top1_accuracy_exemplar_mean_ori'] for i in range(10)],label='history3')
plt.plot(range(1,11),[history4[i]['best_top1_accuracy_exemplar_mean_ori'] for i in range(10)],label='history4')
plt.plot(range(1,11),[history5[i]['best_top1_accuracy_exemplar_mean_ori'] for i in range(10)],label='history5')
plt.ylim([0.3,1])
plt.legend()


In [ ]:
mat=confusion_matrix(data_dict_total['Y_test'],pred_ncm)
sns.heatmap(mat,cmap='bwr',vmin=0,vmax=100)
plt.gcf().set_size_inches((15,12))

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'history.json')) as f:
    history_d=json.load(f)

In [ ]:
plt.plot(range(1,len(history_d[0]['loss_train'])+1),history_d[0]['loss_train'])
plt.plot(range(1,len(history_d[0]['loss_test'])+1),history_d[0]['loss_test'])

In [ ]:
plt.plot(range(1,len(history_d[0]['top1_accuracy_train'])+1),history_d[0]['top1_accuracy_train'])
plt.plot(range(1,len(history_d[0]['top1_accuracy_test'])+1),history_d[0]['top1_accuracy_test'])

In [ ]:
top1_acc_exem_mean=[history_d[i]['best_top1_accuracy_exemplar_mean_test'] for i in range(10)]
top1_acc_theo_mean=[history_d[i]['best_top1_accuracy_theoretical_mean_test'] for i in range(10)]
top1_acc_plain=[history_d[i]['best_top1_accuracy_plain_test'] for i in range(10)]
plt.plot(range(1,len(top1_acc_exem_mean)+1),top1_acc_exem_mean,label='top1_acc_exem_mean')
plt.plot(range(1,len(top1_acc_theo_mean)+1),top1_acc_theo_mean,label='top1_acc_theo_mean')
plt.plot(range(1,len(top1_acc_plain)+1),top1_acc_plain,label='top1_acc_plain')
plt.legend()
plt.ylim([0,1])
plt.gcf().set_size_inches((15,12))

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'theoretical_mean.pkl'),'rb') as f:
    theoretical_mean=pickle.load(f)

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'exemplar_mean.pkl'),'rb') as f:
    exemplar_mean=pickle.load(f)

In [ ]:
with open(os.path.join(fixed_params['base_dir'],'exemplar.pkl'),'rb') as f:
    exemplar=pickle.load(f)

In [ ]:
plt.imshow(exemplar[0,5,...])

In [ ]:
np.all(np.isnan(np.array([np.nan,np.nan])))

In [ ]:
exemplar[1,:,...]==exemplar[1,0:1,...]

In [ ]:
np.linalg.norm(exemplar_mean[0])

In [ ]:
np.linalg.norm(theoretical_mean[0])

In [ ]:
theoretical_mean[0].dot(exemplar_mean[0])

In [ ]:
plt.plot(history_d['global_step'],history_d['loss_train'],label='loss_train')
plt.plot(history_d['global_step'],history_d['loss_test'],label='loss_test')
plt.plot(history_d2['global_step'],history_d2['loss_train'],label='loss_train2')
plt.plot(history_d2['global_step'],history_d2['loss_test'],label='loss_test2')
plt.legend()
plt.gcf().set_size_inches((30,20))

In [ ]:
plt.plot(history_d['global_step'],history_d['top1_accuracy_train'],label='loss_train')
plt.plot(history_d['global_step'],history_d['top1_accuracy_test'],label='loss_test')
plt.plot(history_d2['global_step'],history_d2['top1_accuracy_train'],label='top1_accuracy_train2')
plt.plot(history_d2['global_step'],history_d2['top1_accuracy_test'],label='top1_accuracy_test2')
plt.legend()
plt.gcf().set_size_inches((30,20))

In [ ]:
score_train=sess.run(tf_tensors['loss_train'],feed_dict={tf_tensors['X_train']:X_test_c,tf_tensors['Y_train']:Y_test_c})

In [ ]:
np.mean(score_train)

In [ ]:
tf_networks['test_network'].set_model_params(tf_networks['train_network'].get_all_model_params(sess),sess)

In [ ]:
score_test=sess.run(tf_networks['test_network'].tf_tensors['fc'],feed_dict={tf_tensors['X_test']:X_test_c,tf_tensors['Y_test']:Y_test_c})

In [ ]:
tf.global_variables_initializer().run()

In [ ]:
theoretical_mean=pickle.load(open('cifar100_icarl_debug_Mar11_2/theoretical_mean.pkl','rb'))
feature_map_tensors=dict(X=tf_tensors['X_test'],feature_map=tf_tensors['feature_map_test'])
eval_vals=test_accuracy_evaluation_ncm(X_test_c,Y_test_c,
        theoretical_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
eval_vals

In [ ]:
exemplar_mean=pickle.load(open('cifar100_icarl_debug_Mar11_2/exemplar_mean.pkl','rb'))
feature_map_tensors=dict(X=tf_tensors['X_test'],feature_map=tf_tensors['feature_map_test'])
eval_vals=test_accuracy_evaluation_ncm(X_test_c,Y_test_c,
        exemplar_mean,hyper_params['test_batch_size'],feature_map_tensors,sess)
eval_vals

In [ ]:
data_dict_10=load_cifar10_data()

In [ ]:
meta=unpickle(CIFAR10_META_FILE,encoding='bytes')

In [ ]:
score_train=sess.run(tf_tensors['ranks_of_groud_truth_class_train'],feed_dict={tf_tensors['X_train']:X_train_c,
                                                                  tf_tensors['Y_train']:Y_train_c})

In [ ]:
score_test=sess.run(tf_tensors['ranks_of_groud_truth_class_test'],feed_dict={tf_tensors['X_test']:X_test_c,
                                                                  tf_tensors['Y_test']:Y_test_c})

In [ ]:
np.mean(score_train<5)

In [ ]:
len(tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES, scope='ResNet32_train'))

In [ ]:
len(tf.get_collection(tf.GraphKeys.WEIGHTS, scope='ResNet32_train'))

In [ ]:
[v.shape.as_list() for v in tf_networks['train_network'].tf_variables.values() if v.name.endswith('W:0') ]

In [ ]:
score=sess.run(tf_tensors['ranks_of_groud_truth_class_test'],feed_dict={tf_tensors['X_test']:X_test_c[:],
                                                                  tf_tensors['Y_test']:Y_test_c[:]})
print(score)

In [ ]:
tf_log_var_val={}
tf_log_var_val['loss_test']=0
tf_log_var_val['top1_accuracy_test']=0
tf_log_var_val['top5_accuracy_test']=0
tf_log_var_val['correct_prediction']=0
num_batches_test=int((np.sum(test_idx)/hyper_params['test_batch_size']))
model_params=tf_networks['train_network'].get_all_model_params(sess)
for X_minibatch,Y_minibatch in iterate_minibatches(X_test_c,Y_test_c,hyper_params['test_batch_size'],shuffle=False):
    local_loss,local_top1_accuracy_test,local_top5_accuracy_test,local_ranks_of_groud_truth_class_test=\
    sess.run([tf_tensors['loss_test'],tf_tensors['top1_accuracy_test'],tf_tensors['top5_accuracy_test'],tf_tensors['ranks_of_groud_truth_class_test']],
                feed_dict={tf_tensors['X_test']:X_minibatch,
                           tf_tensors['Y_test']:Y_minibatch})

    tf_log_var_val['loss_test']+=local_loss/num_batches_test
    tf_log_var_val['top1_accuracy_test']+=local_top1_accuracy_test/num_batches_test
    tf_log_var_val['top5_accuracy_test']+=local_top5_accuracy_test/num_batches_test
    tf_log_var_val['correct_prediction']+=np.sum(local_ranks_of_groud_truth_class_test<5)
    print(local_ranks_of_groud_truth_class_test)
print('Pretrain evaluation')
print("\tValidation loss: %f"%(tf_log_var_val['loss_test']))
print("\tTop1 validation accuracy: %f"%(tf_log_var_val['top1_accuracy_test']))
print("\tTop5 validation accuracy: %f"%(tf_log_var_val['top5_accuracy_test']))
print("\tCorrect prediction: %d"%(tf_log_var_val['correct_prediction']))