In [3]:
import os
os.environ['CUDA_VISIBLE_DEVICES']="1"
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from collections import defaultdict
from itertools import combinations
from itertools import chain
from collections import namedtuple
import pickle
import tensorflow as tf
import tflearn
import matplotlib.pyplot as plt
import os.path
import shutil
import inspect
from nn_lib import *
from train_procedures import *
from train_utils import *
from hela10_utils import *
import matplotlib.pyplot as plt
import json
from pprint import pprint
from copy import copy
from sklearn.metrics import confusion_matrix
import seaborn as sns
import sys
np.random.seed(1997)
%load_ext autoreload
%autoreload 2

In [4]:
data_dict_total=load_hela10_data(400)

In [5]:
#non incremental training
hyper_params={'beta':1e-4,
              'initial_lr':0.1,
              'train_batch_size':32,
              'test_batch_size':32,
              'lr_reduction_rate':5,
              'lr_reduction_epoch':[20,30,45],
              'use_fixedsize_exemplar':True,
              'exemplar_set_size':80,
              'final_train_epochs':5,
              'se':True,
              'primary_exemplar':'icarl_exemplar',
              'train_method':'train_with_sample_weight',
              'sample_weight':'half',
              'shuffle_class_ord':False,
              'optimizer':'momentum',
              'ewc_lambda':0,
              'loss_function':'softmax_cross_entropy_with_logits'}
fixed_params={'dataset':'hela10',
              'net_type':'ResNet18',
              'random_seed':1997,
              'total_num_classes':10,
              'base_dir':'./hela10_temp',
              'class_batch_size':2,
              'use_theoretical_mean':True}

In [6]:
tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)

log_prob
log_prob
log_prob


In [7]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)
sess=tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

In [8]:
tf.global_variables_initializer().run()

In [9]:
fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict_total,sess,resume=False,
        save_session=False,save_session_freq=1,save_params=True,evaluation_metric='top1_accuracy',save_history=True,
        num_epochs=55,num_iterations=5,verbose=2,print_freq=1,pretrain_evaluation=0,override_warning=True)

{'base_dir': './hela10_temp',
 'class_batch_size': 2,
 'dataset': 'hela10',
 'net_type': 'ResNet18',
 'random_seed': 1997,
 'total_num_classes': 10,
 'use_theoretical_mean': True}
{'beta': 0.0001,
 'ewc_lambda': 0,
 'exemplar_set_size': 80,
 'final_train_epochs': 5,
 'initial_lr': 0.1,
 'loss_function': 'softmax_cross_entropy_with_logits',
 'lr_reduction_epoch': [20, 30, 45],
 'lr_reduction_rate': 5,
 'optimizer': 'momentum',
 'primary_exemplar': 'icarl_exemplar',
 'sample_weight': 'half',
 'se': True,
 'shuffle_class_ord': False,
 'test_batch_size': 32,
 'train_batch_size': 32,
 'train_method': 'train_with_sample_weight',
 'use_fixedsize_exemplar': True}
data_dict_current: 116
Counter({0: 58, 1: 58})
data_dict_current_weight:
Counter({1: 116})
data_dict_total: 400
Counter({0: 40, 1: 40, 2: 40, 3: 40, 4: 40, 5: 40, 6: 40, 7: 40, 8: 40, 9: 40})
===========Iteration 1=============
Using classes [0, 1]


/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Epoch 1
	Train loss: 0.614188
	Train class loss: 0.143947
	Train reg loss: 0.470241
	Validation loss: 2.762738
	Validation class loss: 2.194570
	Validation reg loss: 0.568168
	Top1 train accuracy: 0.370690
	Top5 train accuracy: 0.663793
	Top1 validation accuracy: 0.500000
	Top5 validation accuracy: 0.500000
[[ 0 40]
 [ 0 40]]
network nan test after epoch
mbi=2826274816
epoch 1, global step 1, time 6.849955
saving model parameters...
Epoch 2
	Train loss: 0.494440
	Train class loss: 0.024256
	Train reg loss: 0.470184
	Validation loss: 2.740970
	Validation class loss: 2.172898
	Validation reg loss: 0.568073
	Top1 train accuracy: 0.775862
	Top5 train accuracy: 0.827586
	Top1 validation accuracy: 0.500000
	Top5 validation accuracy: 0.500000
[[ 0 40]
 [ 0 40]]
network nan test after epoch
mbi=2826274816
epoch 2, global step 2, time 2.289710
Epoch 3
	Train loss: 0.471010
	Train class loss: 0.000916
	Train reg loss: 0.470094
	Validation loss: 4.007023
	Validation class loss: 3.439089
	Validati

epoch 20, global step 20, time 2.395899
lr reduced to 0.020000
Epoch 21
	Train loss: 0.465760
	Train class loss: 0.000011
	Train reg loss: 0.465749
	Validation loss: 0.578170
	Validation class loss: 0.015434
	Validation reg loss: 0.562735
	Top1 train accuracy: 0.827586
	Top5 train accuracy: 0.827586
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[39  1]
 [ 0 40]]
network nan test after epoch
mbi=2826274816
epoch 21, global step 21, time 2.350204
Epoch 22
	Train loss: 0.465715
	Train class loss: 0.000022
	Train reg loss: 0.465693
	Validation loss: 0.573262
	Validation class loss: 0.010594
	Validation reg loss: 0.562668
	Top1 train accuracy: 0.827586
	Top5 train accuracy: 0.827586
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[39  1]
 [ 0 40]]
network nan test after epoch
mbi=2826274816
epoch 22, global step 22, time 2.339649
Epoch 23
	Train loss: 0.465639
	Train class loss: 0.000002
	Train reg loss: 0.465638
	Validation loss: 0.568549

epoch 40, global step 40, time 2.442868
Epoch 41
	Train loss: 0.465167
	Train class loss: 0.000073
	Train reg loss: 0.465094
	Validation loss: 0.562884
	Validation class loss: 0.000904
	Validation reg loss: 0.561980
	Top1 train accuracy: 0.827586
	Top5 train accuracy: 0.827586
	Top1 validation accuracy: 1.000000
	Top5 validation accuracy: 1.000000
[[40  0]
 [ 0 40]]
network nan test after epoch
mbi=2826274816
epoch 41, global step 41, time 2.457488
Epoch 42
	Train loss: 0.465133
	Train class loss: 0.000050
	Train reg loss: 0.465083
	Validation loss: 0.562687
	Validation class loss: 0.000721
	Validation reg loss: 0.561966
	Top1 train accuracy: 0.827586
	Top5 train accuracy: 0.827586
	Top1 validation accuracy: 1.000000
	Top5 validation accuracy: 1.000000
[[40  0]
 [ 0 40]]
network nan test after epoch
mbi=2826274816
epoch 42, global step 42, time 2.436096
Epoch 43
	Train loss: 0.465073
	Train class loss: 0.000001
	Train reg loss: 0.465072
	Validation loss: 0.562913
	Validation class loss

Theoretical mean evaluation
	Best top1 validation accuracy: 1.000000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 1.000000
	Best top5 cumul accuracy: 1.000000
	Best top1 ori accuracy: 1.000000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        40
          1       1.00      1.00      1.00        40

avg / total       1.00      1.00      1.00        80

computing fisher information
conv_1/W:1.096965e-01
batch_norm_1/scale:1.881762e-02
resconv1_2a/W:5.229660e-02
batch_norm_resconv1_2a/scale:4.479470e-03
resconv2_2a/W:1.612375e-02
batch_norm_resconv2_2a/scale:5.593772e-03
squeeze_excitation_2a/fc1/W:1.497347e-07
squeeze_excitation_2a/fc2/W:1.408282e-07
resconv1_2b/W:8.566051e-03
batch_norm_resconv1_2b/scale:1.607201e-03
resconv2_2b/W:5.948155e-03
batch_norm_resconv2_2b/scale:9.305156e-04
squeeze_excitation_2b/fc1/W:3.551569e-08
squeeze_excitation_2b

/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/test_user/.conda/envs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Epoch 1
	Train loss: 0.911955
	Train class loss: 0.361840
	Train reg loss: 0.550115
	Validation loss: 150.110449
	Validation class loss: 149.549323
	Validation reg loss: 0.561130
	Top1 train accuracy: 0.392857
	Top5 train accuracy: 0.964286
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0]
 [40  0  0]
 [40  0  0]]
network nan test after epoch
mbi=2826274816
epoch 1, global step 56, time 3.184243
saving model parameters...
Epoch 2
	Train loss: 0.675495
	Train class loss: 0.126079
	Train reg loss: 0.549416
	Validation loss: 207.849771
	Validation class loss: 207.289255
	Validation reg loss: 0.560509
	Top1 train accuracy: 0.673469
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0]
 [40  0  0]
 [40  0  0]]
network nan test after epoch
mbi=2826274816
epoch 2, global step 57, time 3.217760
Epoch 3
	Train loss: 0.643246
	Train class loss: 0.094408
	Train reg loss: 0.548837
	Validation loss: 214.2

epoch 19, global step 74, time 3.349159
Epoch 20
	Train loss: 0.541931
	Train class loss: 0.003611
	Train reg loss: 0.538320
	Validation loss: 0.643633
	Validation class loss: 0.094476
	Validation reg loss: 0.549158
	Top1 train accuracy: 0.974490
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.962500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 2 37  1]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 20, global step 75, time 3.296248
lr reduced to 0.020000
Epoch 21
	Train loss: 0.540047
	Train class loss: 0.002149
	Train reg loss: 0.537897
	Validation loss: 0.641955
	Validation class loss: 0.092927
	Validation reg loss: 0.549028
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.962500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 2 37  1]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 21, global step 76, time 3.281798
Epoch 22
	Train loss: 0.539622
	Train class loss: 0.001852
	Train reg loss:

epoch 38, global step 93, time 3.333965
Epoch 39
	Train loss: 0.537982
	Train class loss: 0.001525
	Train reg loss: 0.536457
	Validation loss: 0.660012
	Validation class loss: 0.112394
	Validation reg loss: 0.547618
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.937500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 5 35  0]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 39, global step 94, time 3.254738
Epoch 40
	Train loss: 0.538777
	Train class loss: 0.002345
	Train reg loss: 0.536432
	Validation loss: 0.657270
	Validation class loss: 0.109678
	Validation reg loss: 0.547592
	Top1 train accuracy: 0.974490
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.937500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 5 35  0]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 40, global step 95, time 3.358116
Epoch 41
	Train loss: 0.537409
	Train class loss: 0.001003
	Train reg loss: 0.536406
	Validation l

retraining last layer
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Plain evaluation after retrain
	Best top1 validation accuracy: 0.937500
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.962500
	Best top5 cumul accuracy: 1.000000
	Best top1 ori accuracy: 0.987500
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       1.00      0.97      0.99        40
          1       0.89      1.00      0.94        40
          2       0.97      0.88      0.92        40
          3       1.00      1.00      1.00        40

avg / total       0.97      0.96      0.96       160

SVM evaluation
	Best top1 validation accuracy: 0.937500
	Best top1 cumul accuracy: 0.962500
	Best top1 ori accuracy: 0.987500
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       1.00      0.97      0.99        40
          1       0.87      1.00      0.93        40
          2   

epoch 8, global step 118, time 3.287105
saving model parameters...
Epoch 9
	Train loss: 0.549164
	Train class loss: 0.018049
	Train reg loss: 0.531115
	Validation loss: 0.728548
	Validation class loss: 0.186730
	Validation reg loss: 0.541819
	Top1 train accuracy: 0.933673
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.937500
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  1 39  0]
 [ 1  2  0  1 36]]
network nan test after epoch
mbi=2826274816
epoch 9, global step 119, time 3.393947
Epoch 10
	Train loss: 0.545083
	Train class loss: 0.014575
	Train reg loss: 0.530508
	Validation loss: 0.724236
	Validation class loss: 0.183038
	Validation reg loss: 0.541198
	Top1 train accuracy: 0.933673
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.937500
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  1 39  0]
 [ 2  0  2 36]]
network nan test after epoch
mbi=2826274816
epoch 10, global step 120, time 3.

epoch 26, global step 136, time 3.394422
Epoch 27
	Train loss: 0.526163
	Train class loss: 0.002916
	Train reg loss: 0.523247
	Validation loss: 0.806800
	Validation class loss: 0.272726
	Validation reg loss: 0.534074
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.912500
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  4 36  0]
 [ 1  2  0  0 37]]
network nan test after epoch
mbi=2826274816
epoch 27, global step 137, time 3.417169
Epoch 28
	Train loss: 0.526227
	Train class loss: 0.003103
	Train reg loss: 0.523123
	Validation loss: 0.817861
	Validation class loss: 0.283913
	Validation reg loss: 0.533948
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.912500
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  4 36  0]
 [ 1  2  0  0 37]]
network nan test after epoch
mbi=2826274816
epoch 28, global step 138, t

epoch 43, global step 153, time 3.443386
Epoch 44
	Train loss: 0.523297
	Train class loss: 0.000827
	Train reg loss: 0.522470
	Validation loss: 0.781798
	Validation class loss: 0.248458
	Validation reg loss: 0.533340
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.925000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  4 36  0]
 [ 1  1  0  0 38]]
network nan test after epoch
mbi=2826274816
epoch 44, global step 154, time 3.289978
Epoch 45
	Train loss: 0.524298
	Train class loss: 0.001853
	Train reg loss: 0.522445
	Validation loss: 0.785988
	Validation class loss: 0.252674
	Validation reg loss: 0.533314
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.925000
	Top5 validation accuracy: 1.000000
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  4 36  0]
 [ 1  1  0  0 38]]
network nan test after epoch
mbi=2826274816
epoch 45, global step 155, t

Exemplar mean evaluation
	Best top1 validation accuracy: 0.875000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.837500
	Best top5 cumul accuracy: 0.995833
	Best top1 ori accuracy: 0.950000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       1.00      0.97      0.99        40
          1       0.90      0.88      0.89        40
          2       0.87      0.65      0.74        40
          3       0.79      0.78      0.78        40
          4       0.75      0.82      0.79        40
          5       0.76      0.93      0.83        40

avg / total       0.84      0.84      0.84       240

Theoretical mean evaluation
	Best top1 validation accuracy: 0.875000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.841667
	Best top5 cumul accuracy: 0.995833
	Best top1 ori accuracy: 0.950000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
            

epoch 9, global step 174, time 3.367657
saving model parameters...
Epoch 10
	Train loss: 0.535505
	Train class loss: 0.013343
	Train reg loss: 0.522161
	Validation loss: 1.322214
	Validation class loss: 0.794961
	Validation reg loss: 0.527253
	Top1 train accuracy: 0.953608
	Top5 train accuracy: 0.989691
	Top1 validation accuracy: 0.712500
	Top5 validation accuracy: 0.987500
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [12  1  1 24  2]
 [ 5  0  0  2 33]]
network nan test after epoch
mbi=2826274816
epoch 10, global step 175, time 3.286019
Epoch 11
	Train loss: 0.532732
	Train class loss: 0.011162
	Train reg loss: 0.521571
	Validation loss: 1.596669
	Validation class loss: 1.070015
	Validation reg loss: 0.526654
	Top1 train accuracy: 0.969072
	Top5 train accuracy: 0.989691
	Top1 validation accuracy: 0.650000
	Top5 validation accuracy: 0.987500
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 7  1  5 15 12]
 [ 2  0  0  1 37]]
network nan test after epoch
mbi=2826274816
ep

epoch 26, global step 191, time 3.330883
Epoch 27
	Train loss: 0.515727
	Train class loss: 0.000730
	Train reg loss: 0.514997
	Validation loss: 1.256151
	Validation class loss: 0.735862
	Validation reg loss: 0.520290
	Top1 train accuracy: 0.989691
	Top5 train accuracy: 0.989691
	Top1 validation accuracy: 0.812500
	Top5 validation accuracy: 0.987500
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 2  2  1 33  2]
 [ 0  3  0  5 32]]
network nan test after epoch
mbi=2826274816
epoch 27, global step 192, time 3.351988
Epoch 28
	Train loss: 0.515576
	Train class loss: 0.000701
	Train reg loss: 0.514875
	Validation loss: 1.259443
	Validation class loss: 0.739277
	Validation reg loss: 0.520166
	Top1 train accuracy: 0.989691
	Top5 train accuracy: 0.989691
	Top1 validation accuracy: 0.812500
	Top5 validation accuracy: 0.987500
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 2  2  1 33  2]
 [ 0  3  0  5 32]]
network nan test after epoch
mbi=2826274816
epoch 28, global step 193, t

epoch 43, global step 208, time 3.387091
Epoch 44
	Train loss: 0.515008
	Train class loss: 0.000778
	Train reg loss: 0.514230
	Validation loss: 1.260941
	Validation class loss: 0.741369
	Validation reg loss: 0.519572
	Top1 train accuracy: 0.989691
	Top5 train accuracy: 0.989691
	Top1 validation accuracy: 0.837500
	Top5 validation accuracy: 0.987500
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 2  1 35  2]
 [ 3  0  5 32]]
network nan test after epoch
mbi=2826274816
epoch 44, global step 209, time 3.376880
Epoch 45
	Train loss: 0.515055
	Train class loss: 0.000850
	Train reg loss: 0.514206
	Validation loss: 1.257993
	Validation class loss: 0.738446
	Validation reg loss: 0.519547
	Top1 train accuracy: 0.989691
	Top5 train accuracy: 0.989691
	Top1 validation accuracy: 0.837500
	Top5 validation accuracy: 0.987500
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 1  2  1 34  2]
 [ 0  2  0  5 33]]
network nan test after epoch
mbi=2826274816
epoch 45, global step 210, time 3.351931
lr reduced to 0.0

Exemplar mean evaluation
	Best top1 validation accuracy: 0.600000
	Best top5 validation accuracy: 0.987500
	Best top1 cumul accuracy: 0.753125
	Best top5 cumul accuracy: 0.975000
	Best top1 ori accuracy: 0.937500
	Best top5 ori accuracy: 0.975000
	Report string of cumul dataset
             precision    recall  f1-score   support

          0       0.98      1.00      0.99        40
          1       0.85      0.88      0.86        40
          2       0.43      0.40      0.42        40
          3       0.81      0.72      0.76        40
          4       0.73      0.90      0.81        40
          5       0.67      0.95      0.78        40
          6       0.70      0.57      0.63        40
          7       0.92      0.60      0.73        40

avg / total       0.76      0.75      0.75       320

Theoretical mean evaluation
	Best top1 validation accuracy: 0.600000
	Best top5 validation accuracy: 0.987500
	Best top1 cumul accuracy: 0.753125
	Best top5 cumul accuracy: 0.975000
	Best 

epoch 10, global step 230, time 3.359751
Epoch 11
	Train loss: 0.511393
	Train class loss: 0.008295
	Train reg loss: 0.503098
	Validation loss: 0.557946
	Validation class loss: 0.044711
	Validation reg loss: 0.513235
	Top1 train accuracy: 0.974490
	Top5 train accuracy: 0.974490
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[40  0]
 [ 1 39]]
network nan test after epoch
mbi=2826274816
epoch 11, global step 231, time 3.361934
Epoch 12
	Train loss: 0.507366
	Train class loss: 0.004847
	Train reg loss: 0.502519
	Validation loss: 0.549290
	Validation class loss: 0.036648
	Validation reg loss: 0.512642
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 1 39  0]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 12, global step 232, time 3.394850
Epoch 13
	Train loss: 0.509995
	Train class loss: 0.008057
	Train reg loss: 0.501938
	Validation loss: 0.566570
	

epoch 29, global step 249, time 3.402450
Epoch 30
	Train loss: 0.497403
	Train class loss: 0.001011
	Train reg loss: 0.496392
	Validation loss: 0.584623
	Validation class loss: 0.077959
	Validation reg loss: 0.506664
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 1 39  0]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 30, global step 250, time 3.406106
lr reduced to 0.004000
Epoch 31
	Train loss: 0.497676
	Train class loss: 0.001362
	Train reg loss: 0.496314
	Validation loss: 0.579579
	Validation class loss: 0.072940
	Validation reg loss: 0.506640
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 1 39  0]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 31, global step 251, time 3.291445
Epoch 32
	Train loss: 0.497053
	Train class loss: 0.000762
	Train reg lo

epoch 48, global step 268, time 3.358828
Epoch 49
	Train loss: 0.496891
	Train class loss: 0.000937
	Train reg loss: 0.495954
	Validation loss: 0.574630
	Validation class loss: 0.068347
	Validation reg loss: 0.506283
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 1 39  0]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 49, global step 269, time 3.462027
Epoch 50
	Train loss: 0.496843
	Train class loss: 0.000894
	Train reg loss: 0.495949
	Validation loss: 0.573718
	Validation class loss: 0.067440
	Validation reg loss: 0.506278
	Top1 train accuracy: 0.979592
	Top5 train accuracy: 0.979592
	Top1 validation accuracy: 0.987500
	Top5 validation accuracy: 1.000000
[[ 0  0  0]
 [ 1 39  0]
 [ 0  0 40]]
network nan test after epoch
mbi=2826274816
epoch 50, global step 270, time 3.292998
Epoch 51
	Train loss: 0.496711
	Train class loss: 0.000766
	Train reg loss: 0.495944
	Validatio

Final evaluation on all classes (Exemplar mean)
	Best top1 validation accuracy: 0.762500
	Best top5 validation accuracy: 0.995000
Final evaluation on all classes (Theoretical mean)
	Best top1 validation accuracy: 0.765000
	Best top5 validation accuracy: 0.995000


In [25]:
!mv hela10_temp hela10_fix_nodistillation_svm_softmax_balance_2

In [17]:
!mv hela10_temp hela10_fix_nodistillation_svm_softmax_balance

In [ ]:
!mv hela10_temp hela10_fix_distillation_icarl_softmax