In [1]:
import tensorlayer as tl
import os
import matplotlib
import numpy as np
import pandas as pd
from scipy import ndimage
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import tensorflow as tf
import requests
from sklearn import preprocessing
from tensorlayer.prepro import imresize
from itertools import compress

BATCH_SIZE = 20
NUM_CLASSES = 200
NUM_IMAGES_PER_CLASS = 500
NUM_IMAGES = NUM_CLASSES * NUM_IMAGES_PER_CLASS
TRAINING_IMAGES_DIR = './tiny-imagenet-200/train/'
TRAIN_SIZE = NUM_IMAGES

NUM_VAL_IMAGES = 10000
VAL_IMAGES_DIR = './tiny-imagenet-200/val/'

def downsample_fn(x):
    x = imresize(x, size=[32,32], interp='bicubic', mode = None)
    x = x/(255./2.)
    x = x-1.
    return x

def load_tiny_imagenet(path = './tiny-imagenet-200/'):
    data_dict = dict()
    train_dir = path + 'train/'
    test_dir = path + 'val/'
    types = sorted(os.listdir(train_dir))
    train_images = list()
    train_label_name = list()
    for t in types: 
        print(t)
        tmp_path = './tiny-imagenet-200/train/'+t+'/images/'
        file_list = tl.files.load_file_list(path=tmp_path, regx = '.*.JPEG', printable=False)
        tmp=tl.vis.read_images(file_list, path = tmp_path, n_threads=32, printable=False)
#         filter out those images with less dim
        tmp = list(filter(lambda x: x.shape == (64, 64, 3), tmp))
        print(np.shape(tmp))
        
        train_images = train_images+tmp
        tmp_label = list(map(lambda x: x.split('_')[0], file_list))
        train_label_name = train_label_name+tmp_label[:len(tmp)]
#  deal with the test data
    test_file_list= list(map(lambda x: 'val_'+str(x)+'.JPEG', range(10000)))
    test_images = tl.vis.read_images(test_file_list, path = test_dir+'/images/', 
                                     n_threads=32, printable=False)
    test_label_name = pd.read_csv('./tiny-imagenet-200/val/val_annotations.txt', 
                                  sep='\t', header=None)[1].values
    bool_list = list(map(lambda x: x.shape==(64,64,3),test_images))
    test_images = np.array(list(compress(test_images, bool_list)))
    test_label_name = test_label_name[bool_list]
    
    le = preprocessing.LabelEncoder()
    training_le = le.fit(train_label_name)
    train_label = training_le.transform(train_label_name)
    test_label = training_le.transform(test_label_name)
#     reshape images
    print('reshape images')
    train_images = tl.prepro.threading_data(np.array(train_images), fn=downsample_fn)
    test_images = tl.prepro.threading_data(np.array(test_images), fn=downsample_fn)
    
    data_dict['X_test'] = np.array(test_images).astype(np.float32)
    data_dict['X_train'] = np.array(train_images).astype(np.float32)
    data_dict['Y_train'] = train_label.astype(np.int32)
    data_dict['Y_test'] = test_label.astype(np.int32)
    data_dict['X_valid'] = np.zeros([0])
    data_dict['Y_valid'] = np.zeros([0])  
    return data_dict

In [2]:
a = load_tiny_imagenet()

n01443537
(500, 64, 64, 3)
n01629819
(500, 64, 64, 3)
n01641577
(500, 64, 64, 3)
n01644900
(498, 64, 64, 3)
n01698640
(496, 64, 64, 3)
n01742172
(499, 64, 64, 3)
n01768244
(492, 64, 64, 3)
n01770393
(497, 64, 64, 3)
n01774384
(497, 64, 64, 3)
n01774750
(495, 64, 64, 3)
n01784675
(500, 64, 64, 3)
n01855672
(498, 64, 64, 3)
n01882714
(499, 64, 64, 3)
n01910747
(499, 64, 64, 3)
n01917289
(499, 64, 64, 3)
n01944390
(495, 64, 64, 3)
n01945685
(497, 64, 64, 3)
n01950731
(500, 64, 64, 3)
n01983481
(500, 64, 64, 3)
n01984695
(500, 64, 64, 3)
n02002724
(499, 64, 64, 3)
n02056570
(500, 64, 64, 3)
n02058221
(498, 64, 64, 3)
n02074367
(498, 64, 64, 3)
n02085620
(497, 64, 64, 3)
n02094433
(497, 64, 64, 3)
n02099601
(494, 64, 64, 3)
n02099712
(495, 64, 64, 3)
n02106662
(492, 64, 64, 3)
n02113799
(491, 64, 64, 3)
n02123045
(492, 64, 64, 3)
n02123394
(492, 64, 64, 3)
n02124075
(492, 64, 64, 3)
n02125311
(497, 64, 64, 3)
n02129165
(493, 64, 64, 3)
n02132136
(500, 64, 64, 3)
n02165456
(500, 64, 64, 3)
n

In [3]:
import os
os.environ['CUDA_VISIBLE_DEVICES']="1"
import pandas as pd
import numpy as np
from collections import defaultdict
from itertools import combinations
from itertools import chain
from collections import namedtuple
import pickle
import tensorflow as tf
import tflearn
import matplotlib.pyplot as plt
import os.path
import shutil
import inspect
import matplotlib.pyplot as plt
import json
from pprint import pprint
from copy import copy
from nn_lib import *
from train_utils import *
from cifar100_utils import *
from train_procedures import *
np.random.seed(1997)
ALGORITHM=sys.argv[1]
BASE_DIR=sys.argv[2]
if ALGORITHM=='full_data':
    CLASS_BATCH_SIZE=int(sys.argv[3])

In [4]:
data_dict=a

In [5]:
# for testing
ALGORITHM="SupportNet"

In [6]:
#non-incremental settings
if ALGORITHM == 'ft':
    hyper_params={'beta':1e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
#icarl settings
elif ALGORITHM == 'icarl':
    hyper_params={'beta':2e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':5,
                  'se':True,
                  'primary_exemplars':'icarl_exemplars',
                  'train_method':'train_distillation',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':4,
                  'use_theoretical_mean':True}
#SupportNet settings
elif ALGORITHM == 'SupportNet':
    hyper_params={'beta':1e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':5,
                  'se':True,
                  'primary_exemplars':'svm_exemplars',
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':1e-2,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':4,
                  'use_theoretical_mean':True}
#ewc settings
elif ALGORITHM == 'ewc':
    hyper_params={'beta':2e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':1e-2,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
elif ALGORITHM == 'full_data':
    hyper_params={'beta':1e-5,
                  'initial_lr':2,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':CLASS_BATCH_SIZE,
                  'use_theoretical_mean':True}
else:
    assert False

In [7]:
tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)

Use ResNet32


/home/liy0f/incremental_learning_ec/SupportNet/src_image_data/train_procedures.py:50: UserWarning: when use ewc, loss_function should be softmax
  warnings.warn('when use ewc, loss_function should be softmax')


Use ResNet32
Use ResNet32


In [8]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=1)
sess=tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

In [10]:
if ALGORITHM=='full_data':
    fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
            save_params=True,evaluation_metric='top1_accuracy',save_history=True,
            num_epochs=70,num_iterations=1,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=False)
else:
    fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
            save_params=True,evaluation_metric='top1_accuracy',save_history=True,
            num_epochs=70,num_iterations=50,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=False)

{'base_dir': '/run/user/142792/jupyter/kernel-6e07029b-7474-43f5-b80d-8f08ea1e00f9.json',
 'class_batch_size': 4,
 'dataset': 'cifar100',
 'net_type': 'ResNet32',
 'random_seed': 1997,
 'total_num_classes': 100,
 'use_theoretical_mean': True}
{'beta': 1e-05,
 'ewc_lambda': 0.01,
 'exemplars_set_size': 2000,
 'final_train_epochs': 5,
 'initial_lr': 0.1,
 'loss_function': 'sigmoid_cross_entropy_with_logits',
 'lr_reduction_epoch': [49, 63],
 'lr_reduction_rate': 10,
 'optimizer': 'momentum',
 'primary_exemplars': 'svm_exemplars',
 'sample_weight': 0,
 'se': True,
 'shuffle_class_ord': False,
 'test_batch_size': 64,
 'train_batch_size': 64,
 'train_method': 'train_plain',
 'use_fixedsize_exemplars': True}
Y_train class info:
Counter({0: 500, 1: 500, 2: 500, 3: 498})
Y_test class info:
Counter({0: 50, 1: 50, 2: 50, 3: 50})
===========Iteration 1=============
Using classes [0, 1, 2, 3]


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.032392
	Train class loss: 0.014933
	Train reg loss: 0.017459
	Validation loss: 0.032091
	Validation class loss: 0.014631
	Validation reg loss: 0.017459
	Top1 train accuracy: 0.250250
	Top5 train accuracy: 0.250250
	Top1 validation accuracy: 0.250000
	Top5 validation accuracy: 0.250000
[[50  0  0  0]
 [50  0  0  0]
 [50  0  0  0]
 [50  0  0  0]]
Epoch 1
	Train loss: 0.317256
	Train class loss: 0.299890
	Train reg loss: 0.017366
	Validation loss: 0.018284
	Validation class loss: 0.000728
	Validation reg loss: 0.017555
	Top1 train accuracy: 0.219219
	Top5 train accuracy: 0.713714
	Top1 validation accuracy: 0.235000
	Top5 validation accuracy: 0.990000
[[ 0 47  0  3]
 [ 0 47  0  3]
 [ 0 48  0  2]
 [ 0 50  0  0]]
mbi=274448128
time= 5.393447
saving model parameters...
Epoch 2
	Train loss: 0.054987
	Train class loss: 0.037519
	Train reg loss: 0.017468
	Validation loss: 0.017921
	Validation class loss: 0.000308
	Validation reg loss:

Epoch 20
	Train loss: 0.032926
	Train class loss: 0.015508
	Train reg loss: 0.017417
	Validation loss: 0.017702
	Validation class loss: 0.000165
	Validation reg loss: 0.017536
	Top1 train accuracy: 0.621622
	Top5 train accuracy: 0.992993
	Top1 validation accuracy: 0.645000
	Top5 validation accuracy: 1.000000
[[45  0  4  1]
 [ 1 27 10 12]
 [ 2  6 30 12]
 [ 5  5 13 27]]
mbi=274448128
time= 3.144400
saving model parameters...
Epoch 21
	Train loss: 0.032671
	Train class loss: 0.015261
	Train reg loss: 0.017410
	Validation loss: 0.017696
	Validation class loss: 0.000167
	Validation reg loss: 0.017529
	Top1 train accuracy: 0.633133
	Top5 train accuracy: 0.992993
	Top1 validation accuracy: 0.605000
	Top5 validation accuracy: 1.000000
[[45  0  5  0]
 [ 0 23 18  9]
 [ 4  4 33  9]
 [ 5  5 20 20]]
mbi=274448128
time= 3.048376
Epoch 22
	Train loss: 0.032320
	Train class loss: 0.014917
	Train reg loss: 0.017402
	Validation loss: 0.017676
	Validation class loss: 0.000155
	Validation reg loss: 0.0175

Epoch 41
	Train loss: 0.028926
	Train class loss: 0.011681
	Train reg loss: 0.017245
	Validation loss: 0.017489
	Validation class loss: 0.000127
	Validation reg loss: 0.017362
	Top1 train accuracy: 0.728228
	Top5 train accuracy: 0.992492
	Top1 validation accuracy: 0.715000
	Top5 validation accuracy: 1.000000
[[47  0  3  0]
 [ 0 38  7  5]
 [ 2  2 37  9]
 [ 5  5 19 21]]
mbi=274448128
time= 2.954493
Epoch 42
	Train loss: 0.028704
	Train class loss: 0.011467
	Train reg loss: 0.017236
	Validation loss: 0.017476
	Validation class loss: 0.000123
	Validation reg loss: 0.017353
	Top1 train accuracy: 0.730731
	Top5 train accuracy: 0.992492
	Top1 validation accuracy: 0.715000
	Top5 validation accuracy: 1.000000
[[47  0  3  0]
 [ 0 39  4  7]
 [ 1  2 22 25]
 [ 3  5  7 35]]
mbi=274448128
time= 3.032822
Epoch 43
	Train loss: 0.028557
	Train class loss: 0.011329
	Train reg loss: 0.017228
	Validation loss: 0.017468
	Validation class loss: 0.000123
	Validation reg loss: 0.017345
	Top1 train accuracy: 0.

Epoch 62
	Train loss: 0.027629
	Train class loss: 0.010470
	Train reg loss: 0.017159
	Validation loss: 0.017394
	Validation class loss: 0.000114
	Validation reg loss: 0.017280
	Top1 train accuracy: 0.750250
	Top5 train accuracy: 0.992492
	Top1 validation accuracy: 0.745000
	Top5 validation accuracy: 1.000000
[[48  0  2  0]
 [ 0 40  7  3]
 [ 4  3 31 12]
 [ 3  4 13 30]]
mbi=274448128
time= 2.997391
Epoch 63
	Train loss: 0.027710
	Train class loss: 0.010552
	Train reg loss: 0.017158
	Validation loss: 0.017392
	Validation class loss: 0.000113
	Validation reg loss: 0.017279
	Top1 train accuracy: 0.758759
	Top5 train accuracy: 0.992993
	Top1 validation accuracy: 0.760000
	Top5 validation accuracy: 1.000000
[[48  0  2  0]
 [ 0 42  4  4]
 [ 1  4 32 13]
 [ 3  4 13 30]]
mbi=274448128
time= 3.099909
lr reduced to 0.001000
Epoch 64
	Train loss: 0.027457
	Train class loss: 0.010300
	Train reg loss: 0.017158
	Validation loss: 0.017392
	Validation class loss: 0.000113
	Validation reg loss: 0.017279
	

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


69 support_vectors for class 0
support vector not enough for class 0, sampling from previous training set
166 support_vectors for class 1
support vector not enough for class 1, sampling from previous training set
367 support_vectors for class 2
support vector not enough for class 2, sampling from previous training set
397 support_vectors for class 3
support vector not enough for class 3, sampling from previous training set
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Plain evaluation after retrain
	Best top1 validation accuracy: 0.735000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.735000
	Best top5 cumul accuracy: 1.000000
	Best top1 ori accuracy: 0.735000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.86      0.96      0.91        50
           1       0.81      0.84      0.82        50
           2       0.63      0.48      0.55        50
      

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVM evaluation
	Best top1 validation accuracy: 0.740000
	Best top1 cumul accuracy: 0.740000
	Best top1 ori accuracy: 0.740000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.87      0.96      0.91        50
           1       0.81      0.86      0.83        50
           2       0.60      0.66      0.63        50
           3       0.65      0.48      0.55        50

   micro avg       0.74      0.74      0.74       200
   macro avg       0.73      0.74      0.73       200
weighted avg       0.73      0.74      0.73       200

exemplars mean evaluation
	Best top1 validation accuracy: 0.680000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.680000
	Best top5 cumul accuracy: 1.000000
	Best top1 ori accuracy: 0.680000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        50
           1      

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average

Class batch pretrain evaluation (plain method)
	Train loss: 0.017837
	Train class loss: 0.000559
	Train reg loss: 0.017278
	Validation loss: 0.018267
	Validation class loss: 0.000989
	Validation reg loss: 0.017278
	Top1 train accuracy: 0.347390
	Top5 train accuracy: 0.513052
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.025126
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 33 14  0  0  0  0]
 [ 3  9 16 22  0  0  0  0]
 [ 1  1 15 33  0  0  0  0]
 [10  7  8 25  0  0  0  0]]
Epoch 1
	Train loss: 0.052375
	Train class loss: 0.034930
	Train reg loss: 0.017189
	Validation loss: 0.017811
	Validation class loss: 0.000294
	Validation reg loss: 0.017243
	Top1 train accuracy: 0.330070
	Top5 train accuracy: 0.743725
	Top1 validation accuracy: 0.170854
	Top5 validation accuracy: 0.874372
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  4 14  9  8  

Epoch 15
	Train loss: 0.038947
	Train class loss: 0.021654
	Train reg loss: 0.016960
	Validation loss: 0.017606
	Validation class loss: 0.000274
	Validation reg loss: 0.017021
	Top1 train accuracy: 0.468624
	Top5 train accuracy: 0.935994
	Top1 validation accuracy: 0.321608
	Top5 validation accuracy: 0.949749
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  8  3 28  2  7  1]
 [ 2 14  4  2 11 10  6  1]
 [ 0  4  5  2  7  9 21  2]
 [ 2 11  2  2  4  6 18  5]]
mbi=274448128
time= 6.216072
Epoch 16
	Train loss: 0.038785
	Train class loss: 0.021508
	Train reg loss: 0.016945
	Validation loss: 0.017590
	Validation class loss: 0.000243
	Validation reg loss: 0.017005
	Top1 train accuracy: 0.465612
	Top5 train accuracy: 0.929970
	Top1 validation accuracy: 0.376884
	Top5 validation accuracy: 0.939698
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  3  0 30  5 10  1]

Epoch 30
	Train loss: 0.037767
	Train class loss: 0.020585
	Train reg loss: 0.016735
	Validation loss: 0.017480
	Validation class loss: 0.000237
	Validation reg loss: 0.016795
	Top1 train accuracy: 0.500753
	Top5 train accuracy: 0.942520
	Top1 validation accuracy: 0.417085
	Top5 validation accuracy: 0.954774
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  4 29  7  7  2]
 [ 1  8  2  1  9 21  5  3]
 [ 0  1  1  3  8 10 21  6]
 [ 0  8  0  2  2 12 14 12]]
mbi=274448128
time= 6.162629
Epoch 31
	Train loss: 0.037931
	Train class loss: 0.020753
	Train reg loss: 0.016720
	Validation loss: 0.017478
	Validation class loss: 0.000237
	Validation reg loss: 0.016780
	Top1 train accuracy: 0.495733
	Top5 train accuracy: 0.939508
	Top1 validation accuracy: 0.427136
	Top5 validation accuracy: 0.959799
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  7  1 26  3 11  1]

Epoch 45
	Train loss: 0.036945
	Train class loss: 0.019846
	Train reg loss: 0.016522
	Validation loss: 0.017399
	Validation class loss: 0.000246
	Validation reg loss: 0.016582
	Top1 train accuracy: 0.522339
	Top5 train accuracy: 0.945281
	Top1 validation accuracy: 0.432161
	Top5 validation accuracy: 0.934673
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  5  4 29  1  8  2]
 [ 4  4 10  4  8 12  7  1]
 [ 1  0  4  0  6  6 33  0]
 [ 2  0  3  2  5 10 16 12]]
mbi=274448128
time= 6.191574
Epoch 46
	Train loss: 0.036782
	Train class loss: 0.019691
	Train reg loss: 0.016508
	Validation loss: 0.017399
	Validation class loss: 0.000248
	Validation reg loss: 0.016568
	Top1 train accuracy: 0.535392
	Top5 train accuracy: 0.955572
	Top1 validation accuracy: 0.412060
	Top5 validation accuracy: 0.944724
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 1  0  7  3 30  1  5  2]

Epoch 60
	Train loss: 0.036254
	Train class loss: 0.019227
	Train reg loss: 0.016446
	Validation loss: 0.017322
	Validation class loss: 0.000227
	Validation reg loss: 0.016512
	Top1 train accuracy: 0.546436
	Top5 train accuracy: 0.952058
	Top1 validation accuracy: 0.482412
	Top5 validation accuracy: 0.969849
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  2  3 29  3 10  2]
 [ 2  6  3  3  8 15  8  5]
 [ 0  0  3  0  5  6 31  5]
 [ 2  1  2  3  3  7 11 21]]
mbi=274448128
time= 6.135161
Epoch 61
	Train loss: 0.036092
	Train class loss: 0.019066
	Train reg loss: 0.016445
	Validation loss: 0.017327
	Validation class loss: 0.000232
	Validation reg loss: 0.016510
	Top1 train accuracy: 0.553966
	Top5 train accuracy: 0.952560
	Top1 validation accuracy: 0.457286
	Top5 validation accuracy: 0.969849
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  2  3 30  3  9  2]

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


72 support_vectors for class 0
support vector not enough for class 0, sampling from previous training set
158 support_vectors for class 1
support vector not enough for class 1, sampling from previous training set
424 support_vectors for class 2
495 support_vectors for class 3
408 support_vectors for class 4
473 support_vectors for class 5
343 support_vectors for class 6
448 support_vectors for class 7
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Plain evaluation after retrain
	Best top1 validation accuracy: 0.472362
	Best top5 validation accuracy: 0.969849
	Best top1 cumul accuracy: 0.526316
	Best top5 cumul accuracy: 0.969925
	Best top1 ori accuracy: 0.580000
	Best top5 ori accuracy: 0.970000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.89      0.94      0.91        50
           1       0.67      0.90      0.77        50
           2       0.42      0.26      0.32        50
           3       0.44      0.22      0.29        50
           4       0.47      0.57      0.51        49
           5       0.35      0.34      0.35        50
           6       0.39      0.66      0.49        50
           7       0.52      0.32      0.40        50

   micro avg       0.53      0.53      0.53       399
   macro avg       0.52      0.53      0.51       399
weighted avg       0.52      0.53      0.51       399



/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.

SVM evaluation
	Best top1 validation accuracy: 0.482412
	Best top1 cumul accuracy: 0.538847
	Best top1 ori accuracy: 0.595000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.87      0.96      0.91        50
           1       0.67      0.88      0.76        50
           2       0.45      0.30      0.36        50
           3       0.43      0.24      0.31        50
           4       0.47      0.57      0.52        49
           5       0.39      0.28      0.33        50
           6       0.42      0.60      0.50        50
           7       0.47      0.48      0.48        50

   micro avg       0.54      0.54      0.54       399
   macro avg       0.52      0.54      0.52       399
weighted avg       0.52      0.54      0.52       399

exemplars mean evaluation
	Best top1 validation accuracy: 0.386935
	Best top5 validation accuracy: 0.969849
	Best top1 cumul accuracy: 0.458647
	Best top5 cumul accuracy: 0.934837
	Best top1 

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.017125
	Train class loss: 0.000618
	Train reg loss: 0.016507
	Validation loss: 0.017544
	Validation class loss: 0.001038
	Validation reg loss: 0.016507
	Top1 train accuracy: 0.260150
	Top5 train accuracy: 0.479950
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 13  3  1  4  2 10 16  0  0  0  0]
 [ 2  8  1  1  8 13  4 13  0  0  0  0]
 [ 1  8  3  3  2  7 11 15  0  0  0  0]
 [ 1  3  3  4 19  2  7  8  0  0  0  0]]
Epoch 1
	Train loss: 0.057335
	Train class loss: 0.040649
	Train reg loss: 0.016396
	Validation loss: 0.017151
	Validation class loss: 0.000292
	Validation reg loss: 0.016472
	Top1 tr

Epoch 11
	Train loss: 0.043475
	Train class loss: 0.026877
	Train reg loss: 0.016234
	Validation loss: 0.016951
	Validation class loss: 0.000264
	Validation reg loss: 0.016317
	Top1 train accuracy: 0.361905
	Top5 train accuracy: 0.836591
	Top1 validation accuracy: 0.426396
	Top5 validation accuracy: 0.918782
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  1  0  1  3  1 30  8  1  4]
 [ 2  1  0  1  3  4  1 10 21  2  5]
 [ 5  2  2  0  1  3  1 18  9  6  3]
 [ 1  0  0  3  2  4  0  7  2  1 27]]
mbi=274448128
time= 6.089535
saving model parameters...
Epoch 12
	Train loss: 0.043405
	Train class loss: 0.026815
	Train reg loss: 0.016220
	Validation loss: 0.016942
	Validation class loss: 0.000265
	Validation reg loss: 0.016303
	Top1 train accuracy: 0.366667
	Top5 train accuracy: 0.839348

Epoch 22
	Train loss: 0.042471
	Train class loss: 0.025897
	Train reg loss: 0.016088
	Validation loss: 0.016908
	Validation class loss: 0.000261
	Validation reg loss: 0.016171
	Top1 train accuracy: 0.399749
	Top5 train accuracy: 0.851629
	Top1 validation accuracy: 0.426396
	Top5 validation accuracy: 0.913706
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  8  1  0  0  0 31  5  2  3]
 [ 2 12  1  2  0  1  7 19  2  4]
 [ 1 12  0  0  2  0 10  8 11  6]
 [ 1  3  0  7  1  0  7  3  2 23]]
mbi=274448128
time= 6.152465
Epoch 23
	Train loss: 0.042442
	Train class loss: 0.025865
	Train reg loss: 0.016076
	Validation loss: 0.016954
	Validation class loss: 0.000261
	Validation reg loss: 0.016159
	Top1 train accuracy: 0.400752
	Top5 train accuracy: 0.842857
	Top1 validation accuracy: 0.375635
	Top5 validation accuracy: 0.903553
[[ 0  0  0  0  0  0 

Epoch 33
	Train loss: 0.041947
	Train class loss: 0.025347
	Train reg loss: 0.015957
	Validation loss: 0.016928
	Validation class loss: 0.000235
	Validation reg loss: 0.016039
	Top1 train accuracy: 0.412281
	Top5 train accuracy: 0.858145
	Top1 validation accuracy: 0.492386
	Top5 validation accuracy: 0.934010
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 31  9  3  7]
 [ 2  2  0  1  2  2  2  1  9 21  3  5]
 [ 2  3  2  2  0  1  1  0  8 10 15  6]
 [ 1  0  0  1  2  1  2  0  8  1  1 30]]
mbi=274448128
time= 5.940099
Epoch 34
	Train loss: 0.041812
	Train class loss: 0.025213
	Train reg loss: 0.015945
	Validation loss: 0.016934
	Validation class loss: 0.000254
	Validation reg loss: 0.016028
	Top1 train accu

Epoch 44
	Train loss: 0.041303
	Train class loss: 0.024684
	Train reg loss: 0.015836
	Validation loss: 0.016952
	Validation class loss: 0.000247
	Validation reg loss: 0.015919
	Top1 train accuracy: 0.432832
	Top5 train accuracy: 0.866165
	Top1 validation accuracy: 0.492386
	Top5 validation accuracy: 0.898477
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  5  1  0  0  0 36  5  1  2]
 [ 2  6  1  1  2  0  8 27  1  2]
 [ 2 10  1  0  1  2 10  8 14  2]
 [ 1  2  2  3  1  1 13  2  2 20]]
mbi=274448128
time= 6.153132
Epoch 45
	Train loss: 0.041209
	Train class loss: 0.024593
	Train reg loss: 0.015826
	Validation loss: 0.016962
	Validation class loss: 0.000253
	Validation reg loss: 0.015908
	Top1 train accuracy: 0.440852
	Top5 train accuracy: 0.865414
	Top1 validation accuracy: 0.456853
	Top5 validation accuracy: 0.883249
[[ 0  0  0  0  0  0 

Epoch 55
	Train loss: 0.040346
	Train class loss: 0.023774
	Train reg loss: 0.015773
	Validation loss: 0.016892
	Validation class loss: 0.000229
	Validation reg loss: 0.015860
	Top1 train accuracy: 0.455639
	Top5 train accuracy: 0.880451
	Top1 validation accuracy: 0.548223
	Top5 validation accuracy: 0.923858
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  1  0 36  4  2  5]
 [ 2  4  0  2  3  1  1  1  8 22  2  4]
 [ 2  4  2  2  1  1  2  0  6  7 21  2]
 [ 1  0  0  1  2  0  2  0  9  1  2 29]]
mbi=274448128
time= 6.163833
Epoch 56
	Train loss: 0.040342
	Train class loss: 0.023772
	Train reg loss: 0.015772
	Validation loss: 0.016890
	Validation class loss: 0.000229
	Validation reg loss: 0.015859
	Top1 train accu

Epoch 66
	Train loss: 0.039992
	Train class loss: 0.023427
	Train reg loss: 0.015765
	Validation loss: 0.016888
	Validation class loss: 0.000231
	Validation reg loss: 0.015852
	Top1 train accuracy: 0.474687
	Top5 train accuracy: 0.883709
	Top1 validation accuracy: 0.538071
	Top5 validation accuracy: 0.934010
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  1  0 37  4  1  5]
 [ 2  4  0  2  3  2  2  1  7 22  3  2]
 [ 2  5  2  3  1  1  2  0  6  7 19  2]
 [ 1  1  0  1  5  0  1  0  8  1  1 28]]
mbi=274448128
time= 6.365175
Epoch 67
	Train loss: 0.039901
	Train class loss: 0.023337
	Train reg loss: 0.015764
	Validation loss: 0.016883
	Validation class loss: 0.000226
	Validation reg loss: 0.015852
	Top1 train accu

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


103 support_vectors for class 0
support vector not enough for class 0, sampling from previous training set
201 support_vectors for class 1
421 support_vectors for class 2
489 support_vectors for class 3
437 support_vectors for class 4
485 support_vectors for class 5
359 support_vectors for class 6
494 support_vectors for class 7
365 support_vectors for class 8
460 support_vectors for class 9
481 support_vectors for class 10
352 support_vectors for class 11
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Plain evaluation after retrain
	Best top1 validation accuracy: 0.380711
	Best top5 validation accuracy: 0.847716
	Best top1 cumul accuracy: 0.412752
	Best top5 cumul accuracy: 0.874161
	Best top1 ori accuracy: 0.585000
	Best top5 ori accuracy: 0.915000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.75      0.94      0.83        50
           1       0.52      0.82      0.64        50
           2       0.37      0.36      0.36        50
           3       0.27      0.22      0.24        50
           4       0.31      0.29      0.30        49
           5       0.13      0.12      0.13        50
           6       0.35      0.50      0.41        50
           7       0.24      0.18      0.21        50
           8       0.54      0.56      0.55        50
           9       0.52      0.26      0.35        50
          10       0.50      0.18      0.26        50
          11       0.35      0.53      0.42        47

   micro av

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.

SVM evaluation
	Best top1 validation accuracy: 0.395939
	Best top1 cumul accuracy: 0.422819
	Best top1 ori accuracy: 0.570000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.78      0.94      0.85        50
           1       0.48      0.82      0.61        50
           2       0.48      0.30      0.37        50
           3       0.33      0.22      0.27        50
           4       0.30      0.37      0.33        49
           5       0.23      0.20      0.21        50
           6       0.36      0.46      0.40        50
           7       0.33      0.18      0.23        50
           8       0.48      0.60      0.54        50
           9       0.41      0.32      0.36        50
          10       0.41      0.18      0.25        50
          11       0.33      0.49      0.40        47

   micro avg       0.42      0.42      0.42       596
   macro avg       0.41      0.42      0.40       596
weighted avg       0.41      0

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.016499
	Train class loss: 0.000648
	Train reg loss: 0.015852
	Validation loss: 0.016897
	Validation class loss: 0.001046
	Validation reg loss: 0.015852
	Top1 train accuracy: 0.208082
	Top5 train accuracy: 0.436998
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  2  1  4  4  1 16  1 19  0  0  0  0]
 [ 9  0  1  0  4  0  2 18  1  2 13  0  0  0  0]
 [ 2  1  5  2  3  1 14  8  1

Epoch 9
	Train loss: 0.041998
	Train class loss: 0.025854
	Train reg loss: 0.015653
	Validation loss: 0.016395
	Validation class loss: 0.000193
	Validation reg loss: 0.015710
	Top1 train accuracy: 0.431225
	Top5 train accuracy: 0.821787
	Top1 validation accuracy: 0.668342
	Top5 validation accuracy: 0.919598
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  4  2  0  1 35  2  2  3]
 [ 1  1  0  0  0  1  0  0  0  1 37  9  0]
 [ 0  1  2  0  0  1  0  0  0  6  5 30  5]
 [ 1  1  1  1  1  0  0  1  2  4  3  3 31]]
mbi=274448128
time= 6.083576
Epoch 10
	Train loss: 0.041792
	Train class loss: 0.025647
	Train reg loss: 0.015641
	Validation loss: 0.016411
	Va

Epoch 19
	Train loss: 0.040907
	Train class loss: 0.024715
	Train reg loss: 0.015536
	Validation loss: 0.016438
	Validation class loss: 0.000175
	Validation reg loss: 0.015593
	Top1 train accuracy: 0.467369
	Top5 train accuracy: 0.830321
	Top1 validation accuracy: 0.718593
	Top5 validation accuracy: 0.919598
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  1  0  1 39  1  2  3]
 [ 2  0  0  0  1  0  0  1 39  7  0]
 [ 0  1  0  1  1  0  0  3  5 37  2]
 [ 3  0  4  1  1  1  2  4  2  3 28]]
mbi=274448128
time= 6.173855
Epoch 20
	Train loss: 0.040676
	Train class loss: 0.024469
	Train reg loss: 0.015525
	Validation loss: 0.016459
	Validation class loss: 0.000179
	Validation reg loss: 0.015582
	Top1 train accuracy: 0.470884
	Top5 train accuracy: 0.834839
	Top1 validation accuracy:

Epoch 30
	Train loss: 0.040308
	Train class loss: 0.024102
	Train reg loss: 0.015421
	Validation loss: 0.016473
	Validation class loss: 0.000198
	Validation reg loss: 0.015478
	Top1 train accuracy: 0.478163
	Top5 train accuracy: 0.839859
	Top1 validation accuracy: 0.653266
	Top5 validation accuracy: 0.914573
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  1  1  2  1  0  1 35  0  2  6]
 [ 2  1  0  0  0  1  0  0  0  1 32 13  0]
 [ 2  0  2  0  1  1  0  0  0  4  1 35  4]
 [ 4  3  3  1  2  0  1  1  1  1  0  4 28]]
mbi=274448128
time= 6.240128
Epoch 31
	Train loss: 0.040179
	Train class loss: 0.023977
	Train reg loss: 0.015411
	Validation loss: 0.016466
	V

Epoch 40
	Train loss: 0.039875
	Train class loss: 0.023659
	Train reg loss: 0.015326
	Validation loss: 0.016455
	Validation class loss: 0.000163
	Validation reg loss: 0.015384
	Top1 train accuracy: 0.490211
	Top5 train accuracy: 0.847892
	Top1 validation accuracy: 0.738693
	Top5 validation accuracy: 0.929648
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  1  0  2  1 41  0  1  3]
 [ 1  0  0  0  0  1  0  0  0  1 44  3  0]
 [ 0  1  1  0  0  2  0  0  0  7  7 28  4]
 [ 0  1  1  1  1  0  1  2  0  5  2  1 34]]
mbi=274448128
time= 6.171632
Epoch 41
	Train loss: 0.039753
	Train class loss: 0.023531
	Train reg loss: 0.015318
	Validation loss: 0.016418
	V

lr reduced to 0.010000
Epoch 50
	Train loss: 0.038777
	Train class loss: 0.022600
	Train reg loss: 0.015243
	Validation loss: 0.016389
	Validation class loss: 0.000157
	Validation reg loss: 0.015304
	Top1 train accuracy: 0.518072
	Top5 train accuracy: 0.864960
	Top1 validation accuracy: 0.763819
	Top5 validation accuracy: 0.954774
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  2  0 43  2  1  1]
 [ 1  0  0  0  1  0  1 39  8  0]
 [ 0  2  0  1  1  0  3  3 38  2]
 [ 1  1  3  2  2  1  2  2  3 32]]
mbi=274448128
time= 6.142015
saving model parameters...
Epoch 51
	Train loss: 0.038459
	Train class loss: 0.022296
	Train reg loss: 0.015242
	Validation loss: 0.016382
	Validation class loss: 0.000156
	Validation reg loss: 0.015303
	Top1 train accuracy: 0.523845
	Top5 train accuracy: 0.869478
	Top1 validation accuracy: 0.783920
	Top5 

Epoch 62
	Train loss: 0.038557
	Train class loss: 0.022429
	Train reg loss: 0.015233
	Validation loss: 0.016351
	Validation class loss: 0.000156
	Validation reg loss: 0.015294
	Top1 train accuracy: 0.522339
	Top5 train accuracy: 0.869729
	Top1 validation accuracy: 0.763819
	Top5 validation accuracy: 0.939698
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  2  0  1 42  2  1  1]
 [ 1  0  0  0  1  0  0  1 39  8  0]
 [ 1  1  0  1  1  0  0  4  2 38  2]
 [ 1  2  2  2  2  1  0  3  2  1 33]]
mbi=274448128
time= 6.087291
Epoch 63
	Train loss: 0.038427
	Train class loss: 0.022297
	Train reg loss: 0.015232
	Validation loss: 0.016352
	Validation class loss: 0.000159
	Validation reg loss: 0.015293
	Top1 train accuracy: 0.520080
	Top5 train accuracy: 0.869980
	Top1 validation accuracy:

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


148 support_vectors for class 0
204 support_vectors for class 1
435 support_vectors for class 2
494 support_vectors for class 3
438 support_vectors for class 4
494 support_vectors for class 5
401 support_vectors for class 6
495 support_vectors for class 7
370 support_vectors for class 8
457 support_vectors for class 9
484 support_vectors for class 10
398 support_vectors for class 11
261 support_vectors for class 12
251 support_vectors for class 13
309 support_vectors for class 14
470 support_vectors for class 15
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Plain evaluation after retrain
	Best top1 validation accuracy: 0.623116
	Best top5 validation accuracy: 0.844221
	Best top1 cumul accuracy: 0.456604
	Best top5 cumul accuracy: 0.838994
	Best top1 ori accuracy: 0.575000
	Best top5 ori accuracy: 0.885000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.73      0.94      0.82        50
           1       0.49      0.86      0.63        50
           2       0.36      0.26      0.30        50
           3       0.33      0.24      0.28        50
           4       0.35      0.31      0.33        49
           5       0.17      0.12      0.14        50
           6       0.36      0.50      0.42        50
           7       0.27      0.08      0.12        50
           8       0.45      0.64      0.53        50
           9       0.41      0.28      0.33        50
          10       0.43      0.20      0.27        50
          11       0.31      0.38      0.34        47
          12

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.

SVM evaluation
	Best top1 validation accuracy: 0.633166
	Best top1 cumul accuracy: 0.451572
	Best top1 ori accuracy: 0.600000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.77      0.94      0.85        50
           1       0.54      0.88      0.67        50
           2       0.39      0.28      0.33        50
           3       0.42      0.30      0.35        50
           4       0.32      0.31      0.31        49
           5       0.19      0.08      0.11        50
           6       0.39      0.48      0.43        50
           7       0.24      0.10      0.14        50
           8       0.43      0.58      0.50        50
           9       0.41      0.28      0.33        50
          10       0.20      0.10      0.13        50
          11       0.31      0.36      0.33        47
          12       0.39      0.74      0.51        50
          13       0.73      0.82      0.77        50
          14       0.59      0.

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.015971
	Train class loss: 0.000678
	Train reg loss: 0.015293
	Validation loss: 0.016384
	Validation class loss: 0.001091
	Validation reg loss: 0.015293
	Top1 train accuracy: 0.197898
	Top5 train accuracy: 0.414811
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

Epoch 6
	Train loss: 0.044957
	Train class loss: 0.029535
	Train reg loss: 0.015085
	Validation loss: 0.015749
	Validation class loss: 0.000249
	Validation reg loss: 0.015189
	Top1 train accuracy: 0.337753
	Top5 train accuracy: 0.770078
	Top1 validation accuracy: 0.447236
	Top5 validation accuracy: 0.934673
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0

Epoch 13
	Train loss: 0.044125
	Train class loss: 0.028713
	Train reg loss: 0.015000
	Validation loss: 0.015761
	Validation class loss: 0.000237
	Validation reg loss: 0.015103
	Top1 train accuracy: 0.361021
	Top5 train accuracy: 0.782587
	Top1 validation accuracy: 0.537688
	Top5 validation accuracy: 0.944724
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  1  3  1  2  2  0  1  2  0  8 10  2 13]
 [ 0  3  0  0  1  0  0  1  0  1  1  4 23  7  9]
 [ 2  0  0  0  0  0  0  0  0  0  0  2  5 37  4]
 [ 0  3  0  2  0  

Epoch 21
	Train loss: 0.043273
	Train class loss: 0.027823
	Train reg loss: 0.014914
	Validation loss: 0.015812
	Validation class loss: 0.000224
	Validation reg loss: 0.015018
	Top1 train accuracy: 0.381786
	Top5 train accuracy: 0.803353
	Top1 validation accuracy: 0.542714
	Top5 validation accuracy: 0.944724
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  

Epoch 28
	Train loss: 0.042844
	Train class loss: 0.027362
	Train reg loss: 0.014847
	Validation loss: 0.015851
	Validation class loss: 0.000229
	Validation reg loss: 0.014951
	Top1 train accuracy: 0.389042
	Top5 train accuracy: 0.805354
	Top1 validation accuracy: 0.487437
	Top5 validation accuracy: 0.944724
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  8  1  3  0  1  1 11 16  0  4]
 [ 1  2  0  0  1  2  0  1  0  2  3 34  1  3]
 [ 2  0  0  1  0  0  0  0  0  0  2 10 32  3]
 [ 1  2  1  0  6  1  0  0  0  5  2  9  3 20]]
mbi=274448128
time= 6.191435
Epoch 29
	Train loss: 0.042988

Epoch 35
	Train loss: 0.042706
	Train class loss: 0.027189
	Train reg loss: 0.014785
	Validation loss: 0.015846
	Validation class loss: 0.000214
	Validation reg loss: 0.014888
	Top1 train accuracy: 0.410808
	Top5 train accuracy: 0.807105
	Top1 validation accuracy: 0.597990
	Top5 validation accuracy: 0.969849
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  

Epoch 42
	Train loss: 0.042224
	Train class loss: 0.026661
	Train reg loss: 0.014727
	Validation loss: 0.015898
	Validation class loss: 0.000215
	Validation reg loss: 0.014831
	Top1 train accuracy: 0.415812
	Top5 train accuracy: 0.820115
	Top1 validation accuracy: 0.628141
	Top5 validation accuracy: 0.949749
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  

Epoch 49
	Train loss: 0.041872
	Train class loss: 0.026274
	Train reg loss: 0.014673
	Validation loss: 0.015911
	Validation class loss: 0.000199
	Validation reg loss: 0.014777
	Top1 train accuracy: 0.430323
	Top5 train accuracy: 0.823368
	Top1 validation accuracy: 0.603015
	Top5 validation accuracy: 0.964824
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  3  1  2  1  0  1  0  2  0  2  0 17  8  2  9]
 [ 1  0  0  0  1  0  0  0  

Epoch 56
	Train loss: 0.040821
	Train class loss: 0.025277
	Train reg loss: 0.014665
	Validation loss: 0.015856
	Validation class loss: 0.000201
	Validation reg loss: 0.014772
	Top1 train accuracy: 0.453840
	Top5 train accuracy: 0.840881
	Top1 validation accuracy: 0.613065
	Top5 validation accuracy: 0.964824
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  

Epoch 63
	Train loss: 0.040877
	Train class loss: 0.025333
	Train reg loss: 0.014660
	Validation loss: 0.015858
	Validation class loss: 0.000203
	Validation reg loss: 0.014767
	Top1 train accuracy: 0.463848
	Top5 train accuracy: 0.833375
	Top1 validation accuracy: 0.608040
	Top5 validation accuracy: 0.969849
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  

Epoch 70
	Train loss: 0.040637
	Train class loss: 0.025099
	Train reg loss: 0.014659
	Validation loss: 0.015852
	Validation class loss: 0.000201
	Validation reg loss: 0.014766
	Top1 train accuracy: 0.471354
	Top5 train accuracy: 0.840881
	Top1 validation accuracy: 0.648241
	Top5 validation accuracy: 0.969849
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  2  1  0  0  2  2  2  0 20  7  2  7]
 [ 1  0  0  0  0  1  0  0  

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


190 support_vectors for class 0
226 support_vectors for class 1
442 support_vectors for class 2
493 support_vectors for class 3
440 support_vectors for class 4
498 support_vectors for class 5
381 support_vectors for class 6
496 support_vectors for class 7
361 support_vectors for class 8
472 support_vectors for class 9
485 support_vectors for class 10
394 support_vectors for class 11
290 support_vectors for class 12
275 support_vectors for class 13
359 support_vectors for class 14
487 support_vectors for class 15
497 support_vectors for class 16
446 support_vectors for class 17
303 support_vectors for class 18
444 support_vectors for class 19
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Plain evaluation after retrain
	Best top1 validation accuracy: 0.396985
	Best top5 validation accuracy: 0.804020
	Best top1 cumul accuracy: 0.426559
	Best top5 cumul accuracy: 0.779678
	Best top1 ori accuracy: 0.545000
	Best top5 ori accuracy: 0.820000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.60      0.84      0.70        50
           1       0.57      0.80      0.67        50
           2       0.35      0.30      0.32        50
           3       0.28      0.24      0.26        50
           4       0.37      0.39      0.38        49
           5       0.12      0.06      0.08        50
           6       0.31      0.48      0.38        50
           7       0.21      0.08      0.12        50
           8       0.43      0.64      0.52        50
           9       0.35      0.18      0.24        50
          10       0.25      0.14      0.18        50
          11       0.31      0.36      0.33        47
          12

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.

SVM evaluation
	Best top1 validation accuracy: 0.361809
	Best top1 cumul accuracy: 0.424547
	Best top1 ori accuracy: 0.555000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.61      0.88      0.72        50
           1       0.51      0.82      0.63        50
           2       0.29      0.30      0.30        50
           3       0.44      0.22      0.29        50
           4       0.29      0.37      0.32        49
           5       0.21      0.18      0.20        50
           6       0.32      0.46      0.38        50
           7       0.21      0.06      0.09        50
           8       0.49      0.54      0.51        50
           9       0.38      0.28      0.32        50
          10       0.22      0.14      0.17        50
          11       0.33      0.47      0.39        47
          12       0.43      0.72      0.54        50
          13       0.64      0.76      0.70        50
          14       0.60      0.

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Final evaluation on all classes (plain method)
	Top1 train accuracy: 0.044348
	Top5 train accuracy: 0.081148
	Top1 validation accuracy: 0.040073
	Top5 validation accuracy: 0.076688


IndexError: index 107 is out of bounds for axis 1 with size 100