In [1]:
import tensorlayer as tl
import os
import matplotlib
import numpy as np
import pandas as pd
from scipy import ndimage
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import tensorflow as tf
import requests
from sklearn import preprocessing
from tensorlayer.prepro import imresize
from itertools import compress

BATCH_SIZE = 20
NUM_CLASSES = 200
NUM_IMAGES_PER_CLASS = 500
NUM_IMAGES = NUM_CLASSES * NUM_IMAGES_PER_CLASS
TRAINING_IMAGES_DIR = './tiny-imagenet-200/train/'
TRAIN_SIZE = NUM_IMAGES

NUM_VAL_IMAGES = 10000
VAL_IMAGES_DIR = './tiny-imagenet-200/val/'

def downsample_fn(x):
    x = imresize(x, size=[32,32], interp='bicubic', mode = None)
    x = x/(255./2.)
    x = x-1.
    return x

def load_tiny_imagenet(path = './tiny-imagenet-200/'):
    data_dict = dict()
    train_dir = path + 'train/'
    test_dir = path + 'val/'
    types = sorted(os.listdir(train_dir))
    train_images = list()
    train_label_name = list()
    for t in types: 
        print(t)
        tmp_path = './tiny-imagenet-200/train/'+t+'/images/'
        file_list = tl.files.load_file_list(path=tmp_path, regx = '.*.JPEG', printable=False)
        tmp=tl.vis.read_images(file_list, path = tmp_path, n_threads=32, printable=False)
#         filter out those images with less dim
        tmp = list(filter(lambda x: x.shape == (64, 64, 3), tmp))
        print(np.shape(tmp))
        
        train_images = train_images+tmp
        tmp_label = list(map(lambda x: x.split('_')[0], file_list))
        train_label_name = train_label_name+tmp_label[:len(tmp)]
#  deal with the test data
    test_file_list= list(map(lambda x: 'val_'+str(x)+'.JPEG', range(10000)))
    test_images = tl.vis.read_images(test_file_list, path = test_dir+'/images/', 
                                     n_threads=32, printable=False)
    test_label_name = pd.read_csv('./tiny-imagenet-200/val/val_annotations.txt', 
                                  sep='\t', header=None)[1].values
    bool_list = list(map(lambda x: x.shape==(64,64,3),test_images))
    test_images = np.array(list(compress(test_images, bool_list)))
    test_label_name = test_label_name[bool_list]
    
    le = preprocessing.LabelEncoder()
    training_le = le.fit(train_label_name)
    train_label = training_le.transform(train_label_name)
    test_label = training_le.transform(test_label_name)
#     reshape images
    print('reshape images')
    train_images = tl.prepro.threading_data(np.array(train_images), fn=downsample_fn)
    test_images = tl.prepro.threading_data(np.array(test_images), fn=downsample_fn)
    
    data_dict['X_test'] = np.array(test_images).astype(np.float32)
    data_dict['X_train'] = np.array(train_images).astype(np.float32)
    data_dict['Y_train'] = train_label.astype(np.int32)
    data_dict['Y_test'] = test_label.astype(np.int32)
    data_dict['X_valid'] = np.zeros([0])
    data_dict['Y_valid'] = np.zeros([0])  
    return data_dict

In [2]:
a = load_tiny_imagenet()

n01443537
(500, 64, 64, 3)
n01629819
(500, 64, 64, 3)
n01641577
(500, 64, 64, 3)
n01644900
(498, 64, 64, 3)
n01698640
(496, 64, 64, 3)
n01742172
(499, 64, 64, 3)
n01768244
(492, 64, 64, 3)
n01770393
(497, 64, 64, 3)
n01774384
(497, 64, 64, 3)
n01774750
(495, 64, 64, 3)
n01784675
(500, 64, 64, 3)
n01855672
(498, 64, 64, 3)
n01882714
(499, 64, 64, 3)
n01910747
(499, 64, 64, 3)
n01917289
(499, 64, 64, 3)
n01944390
(495, 64, 64, 3)
n01945685
(497, 64, 64, 3)
n01950731
(500, 64, 64, 3)
n01983481
(500, 64, 64, 3)
n01984695
(500, 64, 64, 3)
n02002724
(499, 64, 64, 3)
n02056570
(500, 64, 64, 3)
n02058221
(498, 64, 64, 3)
n02074367
(498, 64, 64, 3)
n02085620
(497, 64, 64, 3)
n02094433
(497, 64, 64, 3)
n02099601
(494, 64, 64, 3)
n02099712
(495, 64, 64, 3)
n02106662
(492, 64, 64, 3)
n02113799
(491, 64, 64, 3)
n02123045
(492, 64, 64, 3)
n02123394
(492, 64, 64, 3)
n02124075
(492, 64, 64, 3)
n02125311
(497, 64, 64, 3)
n02129165
(493, 64, 64, 3)
n02132136
(500, 64, 64, 3)
n02165456
(500, 64, 64, 3)
n

In [3]:
import os
os.environ['CUDA_VISIBLE_DEVICES']="0"
import pandas as pd
import numpy as np
from collections import defaultdict
from itertools import combinations
from itertools import chain
from collections import namedtuple
import pickle
import tensorflow as tf
import tflearn
import matplotlib.pyplot as plt
import os.path
import shutil
import inspect
import matplotlib.pyplot as plt
import json
from pprint import pprint
from copy import copy
from nn_lib import *
from train_utils import *
from cifar100_utils import *
from train_procedures import *
np.random.seed(1997)
ALGORITHM=sys.argv[1]
BASE_DIR=sys.argv[2]
if ALGORITHM=='full_data':
    CLASS_BATCH_SIZE=int(sys.argv[3])

In [4]:
data_dict=a

In [5]:
# for testing
ALGORITHM="icarl"

In [6]:
#non-incremental settings
if ALGORITHM == 'ft':
    hyper_params={'beta':1e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
#icarl settings
elif ALGORITHM == 'icarl':
    hyper_params={'beta':2e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':5,
                  'se':True,
                  'primary_exemplars':'icarl_exemplars',
                  'train_method':'train_distillation',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':4,
                  'use_theoretical_mean':True}
#SupportNet settings
elif ALGORITHM == 'SupportNet':
    hyper_params={'beta':1e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':5,
                  'se':True,
                  'primary_exemplars':'svm_exemplars',
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':1e-2,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':4,
                  'use_theoretical_mean':True}
#ewc settings
elif ALGORITHM == 'ewc':
    hyper_params={'beta':2e-5,
                  'initial_lr':0.1,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':1e-2,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':2,
                  'use_theoretical_mean':True}
elif ALGORITHM == 'full_data':
    hyper_params={'beta':1e-5,
                  'initial_lr':2,
                  'train_batch_size':64,
                  'test_batch_size':64,
                  'lr_reduction_rate':10,
                  'lr_reduction_epoch':[49,63],
                  'use_fixedsize_exemplars':True,
                  'exemplars_set_size':2000,
                  'final_train_epochs':0,
                  'se':True,
                  'primary_exemplars':None,
                  'train_method':'train_plain',
                  'sample_weight':0,
                  'shuffle_class_ord':False,
                  'optimizer':'momentum',
                  'ewc_lambda':0,
                  'loss_function':'sigmoid_cross_entropy_with_logits'}
    fixed_params={'dataset':'cifar100',
                  'net_type':'ResNet32',
                  'random_seed':1997,
                  'total_num_classes':100,
                  'base_dir':BASE_DIR,
                  'class_batch_size':CLASS_BATCH_SIZE,
                  'use_theoretical_mean':True}
else:
    assert False

In [7]:
tf_tensors,tf_variables,tf_networks=build_graph(hyper_params,fixed_params)
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=1)
sess=tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

Use ResNet32
Use ResNet32
Use ResNet32


In [ ]:
if ALGORITHM=='full_data':
    fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
            save_params=True,evaluation_metric='top1_accuracy',save_history=True,
            num_epochs=70,num_iterations=1,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=False)
else:
    fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
            save_params=True,evaluation_metric='top1_accuracy',save_history=True,
            num_epochs=70,num_iterations=50,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=False)

{'base_dir': '/run/user/142792/jupyter/kernel-8abdcddb-305b-4a0a-b576-2f451d5fd97b.json',
 'class_batch_size': 4,
 'dataset': 'cifar100',
 'net_type': 'ResNet32',
 'random_seed': 1997,
 'total_num_classes': 100,
 'use_theoretical_mean': True}
{'beta': 2e-05,
 'ewc_lambda': 0,
 'exemplars_set_size': 2000,
 'final_train_epochs': 5,
 'initial_lr': 0.1,
 'loss_function': 'sigmoid_cross_entropy_with_logits',
 'lr_reduction_epoch': [49, 63],
 'lr_reduction_rate': 10,
 'optimizer': 'momentum',
 'primary_exemplars': 'icarl_exemplars',
 'sample_weight': 0,
 'se': True,
 'shuffle_class_ord': False,
 'test_batch_size': 64,
 'train_batch_size': 64,
 'train_method': 'train_distillation',
 'use_fixedsize_exemplars': True}
Y_train class info:
Counter({0: 500, 1: 500, 2: 500, 3: 498})
Y_test class info:
Counter({0: 50, 1: 50, 2: 50, 3: 50})
===========Iteration 1=============
Using classes [0, 1, 2, 3]


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.049851
	Train class loss: 0.014933
	Train reg loss: 0.034918
	Validation loss: 0.049550
	Validation class loss: 0.014631
	Validation reg loss: 0.034918
	Top1 train accuracy: 0.250250
	Top5 train accuracy: 0.250250
	Top1 validation accuracy: 0.250000
	Top5 validation accuracy: 0.250000
[[50  0  0  0]
 [50  0  0  0]
 [50  0  0  0]
 [50  0  0  0]]
Epoch 1
	Train loss: 0.334633
	Train class loss: 0.299907
	Train reg loss: 0.034726
	Validation loss: 0.035825
	Validation class loss: 0.000730
	Validation reg loss: 0.035095
	Top1 train accuracy: 0.219720
	Top5 train accuracy: 0.713714
	Top1 validation accuracy: 0.235000
	Top5 validation accuracy: 0.990000
[[ 0 47  0  3]
 [ 0 47  0  3]
 [ 0 48  0  2]
 [ 0 50  0  0]]
mbi=275348736
time= 5.505293
saving model parameters...
Epoch 2
	Train loss: 0.072449
	Train class loss: 0.037538
	Train reg loss: 0.034911
	Validation loss: 0.035497
	Validation class loss: 0.000308
	Validation reg loss:

Epoch 20
	Train loss: 0.049964
	Train class loss: 0.015538
	Train reg loss: 0.034426
	Validation loss: 0.034816
	Validation class loss: 0.000166
	Validation reg loss: 0.034650
	Top1 train accuracy: 0.623123
	Top5 train accuracy: 0.992993
	Top1 validation accuracy: 0.650000
	Top5 validation accuracy: 1.000000
[[45  0  4  1]
 [ 1 27 10 12]
 [ 2  6 30 12]
 [ 5  5 12 28]]
mbi=275348736
time= 3.097222
saving model parameters...
Epoch 21
	Train loss: 0.049675
	Train class loss: 0.015286
	Train reg loss: 0.034390
	Validation loss: 0.034781
	Validation class loss: 0.000167
	Validation reg loss: 0.034614
	Top1 train accuracy: 0.636136
	Top5 train accuracy: 0.992993
	Top1 validation accuracy: 0.610000
	Top5 validation accuracy: 1.000000
[[45  0  5  0]
 [ 0 23 18  9]
 [ 4  4 33  9]
 [ 5  5 19 21]]
mbi=275348736
time= 3.016890
Epoch 22
	Train loss: 0.049295
	Train class loss: 0.014941
	Train reg loss: 0.034354
	Validation loss: 0.034732
	Validation class loss: 0.000155
	Validation reg loss: 0.0345

Epoch 41
	Train loss: 0.045370
	Train class loss: 0.011720
	Train reg loss: 0.033650
	Validation loss: 0.033995
	Validation class loss: 0.000127
	Validation reg loss: 0.033868
	Top1 train accuracy: 0.728228
	Top5 train accuracy: 0.992492
	Top1 validation accuracy: 0.720000
	Top5 validation accuracy: 1.000000
[[47  0  3  0]
 [ 0 39  7  4]
 [ 2  2 37  9]
 [ 5  3 21 21]]
mbi=275348736
time= 3.069772
Epoch 42
	Train loss: 0.045113
	Train class loss: 0.011500
	Train reg loss: 0.033612
	Validation loss: 0.033953
	Validation class loss: 0.000123
	Validation reg loss: 0.033830
	Top1 train accuracy: 0.732733
	Top5 train accuracy: 0.992492
	Top1 validation accuracy: 0.725000
	Top5 validation accuracy: 1.000000
[[47  0  3  0]
 [ 0 40  4  6]
 [ 1  2 22 25]
 [ 3  5  6 36]]
mbi=275348736
time= 3.239684
Epoch 43
	Train loss: 0.044933
	Train class loss: 0.011358
	Train reg loss: 0.033575
	Validation loss: 0.033915
	Validation class loss: 0.000123
	Validation reg loss: 0.033792
	Top1 train accuracy: 0.

Epoch 62
	Train loss: 0.043783
	Train class loss: 0.010500
	Train reg loss: 0.033283
	Validation loss: 0.033631
	Validation class loss: 0.000115
	Validation reg loss: 0.033516
	Top1 train accuracy: 0.751251
	Top5 train accuracy: 0.992492
	Top1 validation accuracy: 0.745000
	Top5 validation accuracy: 1.000000
[[48  0  2  0]
 [ 0 40  7  3]
 [ 4  3 31 12]
 [ 3  4 13 30]]
mbi=275348736
time= 3.086560
Epoch 63
	Train loss: 0.043856
	Train class loss: 0.010576
	Train reg loss: 0.033280
	Validation loss: 0.033626
	Validation class loss: 0.000113
	Validation reg loss: 0.033512
	Top1 train accuracy: 0.753754
	Top5 train accuracy: 0.992993
	Top1 validation accuracy: 0.750000
	Top5 validation accuracy: 1.000000
[[48  0  2  0]
 [ 0 42  4  4]
 [ 2  5 30 13]
 [ 3  4 13 30]]
mbi=275348736
time= 3.006418
lr reduced to 0.001000
Epoch 64
	Train loss: 0.043613
	Train class loss: 0.010336
	Train reg loss: 0.033277
	Validation loss: 0.033625
	Validation class loss: 0.000113
	Validation reg loss: 0.033512
	

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


66 support_vectors for class 0
support vector not enough for class 0, sampling from previous training set
164 support_vectors for class 1
support vector not enough for class 1, sampling from previous training set
368 support_vectors for class 2
support vector not enough for class 2, sampling from previous training set
402 support_vectors for class 3
support vector not enough for class 3, sampling from previous training set
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Plain evaluation after retrain
	Best top1 validation accuracy: 0.740000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.740000
	Best top5 cumul accuracy: 1.000000
	Best top1 ori accuracy: 0.740000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.89      0.96      0.92        50
           1       0.83      0.86      0.84        50
           2       0.60      0.52      0.56        50
      

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVM evaluation
	Best top1 validation accuracy: 0.740000
	Best top1 cumul accuracy: 0.740000
	Best top1 ori accuracy: 0.740000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.92      0.96      0.94        50
           1       0.84      0.82      0.83        50
           2       0.58      0.62      0.60        50
           3       0.61      0.56      0.58        50

   micro avg       0.74      0.74      0.74       200
   macro avg       0.74      0.74      0.74       200
weighted avg       0.74      0.74      0.74       200

exemplars mean evaluation
	Best top1 validation accuracy: 0.680000
	Best top5 validation accuracy: 1.000000
	Best top1 cumul accuracy: 0.680000
	Best top5 cumul accuracy: 1.000000
	Best top1 ori accuracy: 0.680000
	Best top5 ori accuracy: 1.000000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        50
           1      

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average

Class batch pretrain evaluation (plain method)
	Train loss: 0.034053
	Train class loss: 0.000544
	Train reg loss: 0.033510
	Validation loss: 0.034490
	Validation class loss: 0.000980
	Validation reg loss: 0.033510
	Top1 train accuracy: 0.387550
	Top5 train accuracy: 0.512550
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.020101
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 33 14  0  0  0  0]
 [ 3  8 16 23  0  0  0  0]
 [ 1  1 15 33  0  0  0  0]
 [ 9  7  8 26  0  0  0  0]]
Epoch 1
	Train loss: 0.070924
	Train class loss: 0.037607
	Train reg loss: 0.033316
	Validation loss: 0.033796
	Validation class loss: 0.000395
	Validation reg loss: 0.033400
	Top1 train accuracy: 0.374247
	Top5 train accuracy: 0.746486
	Top1 validation accuracy: 0.010050
	Top5 validation accuracy: 0.783920
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 3  0 34 11  0  

Epoch 15
	Train loss: 0.058281
	Train class loss: 0.026032
	Train reg loss: 0.032249
	Validation loss: 0.032700
	Validation class loss: 0.000359
	Validation reg loss: 0.032340
	Top1 train accuracy: 0.385040
	Top5 train accuracy: 0.925954
	Top1 validation accuracy: 0.050251
	Top5 validation accuracy: 0.889447
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 32 10  3  0  2  0]
 [ 4  7 17 21  0  1  0  0]
 [ 1  0 14 29  0  0  6  0]
 [ 8  7  8 25  0  0  2  0]]
mbi=275348736
time= 6.609191
saving model parameters...
Epoch 16
	Train loss: 0.058118
	Train class loss: 0.025944
	Train reg loss: 0.032174
	Validation loss: 0.032630
	Validation class loss: 0.000365
	Validation reg loss: 0.032265
	Top1 train accuracy: 0.389307
	Top5 train accuracy: 0.922440
	Top1 validation accuracy: 0.030151
	Top5 validation accuracy: 0.874372
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]

Epoch 30
	Train loss: 0.056534
	Train class loss: 0.025397
	Train reg loss: 0.031137
	Validation loss: 0.031566
	Validation class loss: 0.000340
	Validation reg loss: 0.031226
	Top1 train accuracy: 0.409388
	Top5 train accuracy: 0.938002
	Top1 validation accuracy: 0.105528
	Top5 validation accuracy: 0.909548
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 30 10  6  0  1  0]
 [ 4  6 13 19  2  3  3  0]
 [ 4  0 13 21  1  0 11  0]
 [ 6  6  8 22  0  1  6  1]]
mbi=275348736
time= 6.718896
saving model parameters...
Epoch 31
	Train loss: 0.056519
	Train class loss: 0.025455
	Train reg loss: 0.031065
	Validation loss: 0.031500
	Validation class loss: 0.000347
	Validation reg loss: 0.031152
	Top1 train accuracy: 0.405120
	Top5 train accuracy: 0.928213
	Top1 validation accuracy: 0.095477
	Top5 validation accuracy: 0.884422
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]

Epoch 45
	Train loss: 0.055022
	Train class loss: 0.024960
	Train reg loss: 0.030062
	Validation loss: 0.030491
	Validation class loss: 0.000343
	Validation reg loss: 0.030147
	Top1 train accuracy: 0.435492
	Top5 train accuracy: 0.937249
	Top1 validation accuracy: 0.130653
	Top5 validation accuracy: 0.894472
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 23 13  9  0  2  0]
 [ 4  5 13 23  2  1  2  0]
 [ 1  0 11 24  0  0 14  0]
 [ 7  3  5 28  1  0  4  2]]
mbi=275348736
time= 6.864827
Epoch 46
	Train loss: 0.054915
	Train class loss: 0.024923
	Train reg loss: 0.029992
	Validation loss: 0.030439
	Validation class loss: 0.000362
	Validation reg loss: 0.030077
	Top1 train accuracy: 0.435994
	Top5 train accuracy: 0.943273
	Top1 validation accuracy: 0.080402
	Top5 validation accuracy: 0.844221
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 31 10  5  0  1  0]

Epoch 60
	Train loss: 0.054196
	Train class loss: 0.024523
	Train reg loss: 0.029674
	Validation loss: 0.030131
	Validation class loss: 0.000341
	Validation reg loss: 0.029790
	Top1 train accuracy: 0.447540
	Top5 train accuracy: 0.942771
	Top1 validation accuracy: 0.150754
	Top5 validation accuracy: 0.899497
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 26 10 10  0  1  0]
 [ 4  7 12 21  2  1  3  0]
 [ 1  0 13 19  0  0 16  1]
 [ 7  6  5 23  1  0  5  3]]
mbi=275348736
time= 6.629209
Epoch 61
	Train loss: 0.054165
	Train class loss: 0.024498
	Train reg loss: 0.029667
	Validation loss: 0.030126
	Validation class loss: 0.000344
	Validation reg loss: 0.029783
	Top1 train accuracy: 0.452058
	Top5 train accuracy: 0.941767
	Top1 validation accuracy: 0.155779
	Top5 validation accuracy: 0.894472
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0 25 10 11  0  1  0]

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


93 support_vectors for class 0
support vector not enough for class 0, sampling from previous training set
194 support_vectors for class 1
support vector not enough for class 1, sampling from previous training set
450 support_vectors for class 2
497 support_vectors for class 3
405 support_vectors for class 4
462 support_vectors for class 5
326 support_vectors for class 6
444 support_vectors for class 7
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Plain evaluation after retrain
	Best top1 validation accuracy: 0.462312
	Best top5 validation accuracy: 0.929648
	Best top1 cumul accuracy: 0.508772
	Best top5 cumul accuracy: 0.947368
	Best top1 ori accuracy: 0.555000
	Best top5 ori accuracy: 0.965000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.85      0.94      0.90        50
           1       0.74      0.84      0.79        50
           2       0.34      0.26      0.30        50
           3       0.28      0.18      0.22        50
           4       0.44      0.57      0.50        49
           5       0.33      0.36      0.34        50
           6       0.42      0.56      0.48        50
           7       0.56      0.36      0.44        50

   micro avg       0.51      0.51      0.51       399
   macro avg       0.50      0.51      0.49       399
weighted avg       0.50      0.51      0.49       399



/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.

SVM evaluation
	Best top1 validation accuracy: 0.487437
	Best top1 cumul accuracy: 0.518797
	Best top1 ori accuracy: 0.550000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.88      0.92      0.90        50
           1       0.76      0.76      0.76        50
           2       0.40      0.32      0.36        50
           3       0.36      0.20      0.26        50
           4       0.42      0.61      0.50        49
           5       0.31      0.32      0.31        50
           6       0.49      0.58      0.53        50
           7       0.47      0.44      0.45        50

   micro avg       0.52      0.52      0.52       399
   macro avg       0.51      0.52      0.51       399
weighted avg       0.51      0.52      0.51       399

exemplars mean evaluation
	Best top1 validation accuracy: 0.356784
	Best top5 validation accuracy: 0.929648
	Best top1 cumul accuracy: 0.426065
	Best top5 cumul accuracy: 0.924812
	Best top1 

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.030429
	Train class loss: 0.000666
	Train reg loss: 0.029764
	Validation loss: 0.030863
	Validation class loss: 0.001099
	Validation reg loss: 0.029764
	Top1 train accuracy: 0.237093
	Top5 train accuracy: 0.480451
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  9 13 18  0  0  4  5  0  0  0  0]
 [ 2 15  8 21  0  2  1  1  0  0  0  0]
 [ 5  7  7 21  0  3  3  4  0  0  0  0]
 [ 2  1 23 15  3  0  1  2  0  0  0  0]]
Epoch 1
	Train loss: 0.082816
	Train class loss: 0.053274
	Train reg loss: 0.029542
	Validation loss: 0.030107
	Validation class loss: 0.000450
	Validation reg loss: 0.029657
	Top1 tr

Epoch 11
	Train loss: 0.070139
	Train class loss: 0.041298
	Train reg loss: 0.028841
	Validation loss: 0.029398
	Validation class loss: 0.000432
	Validation reg loss: 0.028966
	Top1 train accuracy: 0.232581
	Top5 train accuracy: 0.751880
	Top1 validation accuracy: 0.005076
	Top5 validation accuracy: 0.614213
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  8 14 18  0  0  4  4  0  0  0  1]
 [ 2 13  7 21  2  2  1  2  0  0  0  0]
 [ 5  8  8 19  0  2  5  2  1  0  0  0]
 [ 2  1 24 10  4  0  3  2  0  0  0  1]]
mbi=275348736
time= 6.904777
Epoch 12
	Train loss: 0.070012
	Train class loss: 0.041239
	Train reg loss: 0.028773
	Validation loss: 0.029325
	Validation class loss: 0.000427
	Validation reg loss: 0.028898
	Top1 train accu

Epoch 22
	Train loss: 0.068819
	Train class loss: 0.040713
	Train reg loss: 0.028106
	Validation loss: 0.028654
	Validation class loss: 0.000426
	Validation reg loss: 0.028228
	Top1 train accuracy: 0.249875
	Top5 train accuracy: 0.774687
	Top1 validation accuracy: 0.040609
	Top5 validation accuracy: 0.700508
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  7  9 19  0  0  6  4  1  2  0  1]
 [ 2  9  5 23  0  1  2  2  0  5  0  1]
 [ 5  7  6 20  0  2  3  3  3  0  1  0]
 [ 3  1 23 12  2  0  3  2  0  0  0  1]]
mbi=275348736
time= 6.700868
Epoch 23
	Train loss: 0.068635
	Train class loss: 0.040594
	Train reg loss: 0.028040
	Validation loss: 0.028591
	Validation class loss: 0.000428
	Validation reg loss: 0.028162
	Top1 train accu

Epoch 33
	Train loss: 0.067608
	Train class loss: 0.040215
	Train reg loss: 0.027393
	Validation loss: 0.027930
	Validation class loss: 0.000418
	Validation reg loss: 0.027513
	Top1 train accuracy: 0.279950
	Top5 train accuracy: 0.799749
	Top1 validation accuracy: 0.096447
	Top5 validation accuracy: 0.695431
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6 10 16  0  0  2  0 12  2  1  1]
 [ 2 11  6 23  0  2  0  1  2  3  0  0]
 [ 5  8  5 22  0  3  1  1  4  0  1  0]
 [ 2  1 23 14  1  0  1  2  0  0  0  3]]
mbi=275348736
time= 6.801456
Epoch 34
	Train loss: 0.067599
	Train class loss: 0.040270
	Train reg loss: 0.027330
	Validation loss: 0.027866
	Validation class loss: 0.000417
	Validation reg loss: 0.027448
	Top1 train accu

Epoch 44
	Train loss: 0.066314
	Train class loss: 0.039611
	Train reg loss: 0.026703
	Validation loss: 0.027227
	Validation class loss: 0.000407
	Validation reg loss: 0.026820
	Top1 train accuracy: 0.319298
	Top5 train accuracy: 0.802757
	Top1 validation accuracy: 0.147208
	Top5 validation accuracy: 0.725888
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6 10 13  0  0  4  1 12  2  1  1]
 [ 2 10  6 21  1  1  0  0  1  8  0  0]
 [ 4  8  7 18  0  2  3  1  2  1  3  1]
 [ 1  1 21 10  2  0  3  2  0  0  1  6]]
mbi=275348736
time= 7.067404
Epoch 45
	Train loss: 0.066176
	Train class loss: 0.039535
	Train reg loss: 0.026642
	Validation loss: 0.027164
	Validation class loss: 0.000407
	Validation reg loss: 0.026758
	Top1 train accu

Epoch 55
	Train loss: 0.065388
	Train class loss: 0.039056
	Train reg loss: 0.026332
	Validation loss: 0.026874
	Validation class loss: 0.000399
	Validation reg loss: 0.026475
	Top1 train accuracy: 0.341103
	Top5 train accuracy: 0.818045
	Top1 validation accuracy: 0.218274
	Top5 validation accuracy: 0.746193
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  9 13  0  0  2  0 20  1  1  1]
 [ 2  6  6 23  0  2  0  0  2  8  0  1]
 [ 4  7  7 14  0  3  3  1  2  1  7  1]
 [ 3  1 19 12  1  0  2  1  0  0  0  8]]
mbi=275348736
time= 6.765900
Epoch 56
	Train loss: 0.065412
	Train class loss: 0.039086
	Train reg loss: 0.026326
	Validation loss: 0.026867
	Validation class loss: 0.000398
	Validation reg loss: 0.026469
	Top1 train accu

Epoch 66
	Train loss: 0.065135
	Train class loss: 0.038856
	Train reg loss: 0.026279
	Validation loss: 0.026822
	Validation class loss: 0.000398
	Validation reg loss: 0.026424
	Top1 train accuracy: 0.345865
	Top5 train accuracy: 0.824812
	Top1 validation accuracy: 0.213198
	Top5 validation accuracy: 0.730964
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  9 13  0  0  2  0 20  1  1  1]
 [ 2  7  6 24  0  2  0  0  2  6  0  1]
 [ 4  7  7 15  0  3  3  1  2  0  7  1]
 [ 3  1 18 12  1  0  2  1  0  0  0  9]]
mbi=275348736
time= 6.720714
Epoch 67
	Train loss: 0.065154
	Train class loss: 0.038875
	Train reg loss: 0.026278
	Validation loss: 0.026822
	Validation class loss: 0.000398
	Validation reg loss: 0.026424
	Top1 train accu

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


126 support_vectors for class 0
support vector not enough for class 0, sampling from previous training set
232 support_vectors for class 1
457 support_vectors for class 2
497 support_vectors for class 3
435 support_vectors for class 4
486 support_vectors for class 5
390 support_vectors for class 6
493 support_vectors for class 7
382 support_vectors for class 8
440 support_vectors for class 9
458 support_vectors for class 10
345 support_vectors for class 11
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Plain evaluation after retrain
	Best top1 validation accuracy: 0.416244
	Best top5 validation accuracy: 0.802030
	Best top1 cumul accuracy: 0.407718
	Best top5 cumul accuracy: 0.859060
	Best top1 ori accuracy: 0.535000
	Best top5 ori accuracy: 0.910000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.72      0.94      0.82        50
           1       0.55      0.72      0.63        50
           2       0.28      0.30      0.29        50
           3       0.26      0.18      0.21        50
           4       0.33      0.39      0.36        49
           5       0.18      0.18      0.18        50
           6       0.37      0.44      0.40        50
           7       0.19      0.08      0.11        50
           8       0.55      0.62      0.58        50
           9       0.39      0.22      0.28        50
          10       0.42      0.30      0.35        50
          11       0.35      0.53      0.42        47

   micro av

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.

SVM evaluation
	Best top1 validation accuracy: 0.461929
	Best top1 cumul accuracy: 0.426174
	Best top1 ori accuracy: 0.525000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.88      0.92      0.90        50
           1       0.66      0.70      0.68        50
           2       0.32      0.32      0.32        50
           3       0.32      0.16      0.21        50
           4       0.32      0.37      0.34        49
           5       0.25      0.28      0.26        50
           6       0.40      0.38      0.39        50
           7       0.33      0.14      0.20        50
           8       0.52      0.60      0.56        50
           9       0.38      0.42      0.40        50
          10       0.30      0.26      0.28        50
          11       0.35      0.57      0.43        47

   micro avg       0.43      0.43      0.43       596
   macro avg       0.42      0.43      0.41       596
weighted avg       0.42      0

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.027169
	Train class loss: 0.000747
	Train reg loss: 0.026422
	Validation loss: 0.027619
	Validation class loss: 0.001197
	Validation reg loss: 0.026422
	Top1 train accuracy: 0.195783
	Top5 train accuracy: 0.435241
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17 22  0  2  2  0  0  3  0  4  0

Epoch 8
	Train loss: 0.076626
	Train class loss: 0.050791
	Train reg loss: 0.025835
	Validation loss: 0.026390
	Validation class loss: 0.000481
	Validation reg loss: 0.025909
	Top1 train accuracy: 0.240211
	Top5 train accuracy: 0.751004
	Top1 validation accuracy: 0.160804
	Top5 validation accuracy: 0.708543
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 14 17  0  2  0  1  0  3 13  0  0  0]
 [28  0  5  2  0  1  0  0  0  0  0 13  1  0]
 [ 7  1 15  6  1  7  2  0  0  1  2  3  5  0]
 [ 6  0 17 16  1  1  0  1  1  4  1  0  0  1]]
mbi=275348736
time= 6.965641
saving model parameters...
Epoc

Epoch 17
	Train loss: 0.075070
	Train class loss: 0.049761
	Train reg loss: 0.025309
	Validation loss: 0.025847
	Validation class loss: 0.000465
	Validation reg loss: 0.025382
	Top1 train accuracy: 0.304719
	Top5 train accuracy: 0.767068
	Top1 validation accuracy: 0.316583
	Top5 validation accuracy: 0.753769
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  8  0  0  1  2  0  2 27  0  0  0]
 [22  0  4  1  0  0  1  0  0  0  1 19  2  0]
 [ 7  1 12  6  0  0  6  0  0  1  2  1 14  0]
 [ 4  0 15 16  1  1  1  1  1  3  2  0  1  3]]
mbi=275348736
time= 6.658060
Epoch 18
	Train loss: 0.074980

Epoch 26
	Train loss: 0.073919
	Train class loss: 0.049125
	Train reg loss: 0.024794
	Validation loss: 0.025315
	Validation class loss: 0.000450
	Validation reg loss: 0.024866
	Top1 train accuracy: 0.338855
	Top5 train accuracy: 0.791165
	Top1 validation accuracy: 0.412060
	Top5 validation accuracy: 0.773869
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  9  0  0  0  0  0  4  0  1 26  0  1  0]
 [14  0  2  4  0  0  0  1  

Epoch 35
	Train loss: 0.072958
	Train class loss: 0.048668
	Train reg loss: 0.024291
	Validation loss: 0.024815
	Validation class loss: 0.000455
	Validation reg loss: 0.024360
	Top1 train accuracy: 0.369729
	Top5 train accuracy: 0.789408
	Top1 validation accuracy: 0.402010
	Top5 validation accuracy: 0.763819
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 13 10  0  0  0  0  1  0  2 23  0  1  0]
 [15  0  2  2  0  0  1  0  0  0  1  0 27  2  0]
 [ 3  1  6  6  1  0  5  1  0  0  0  2  0 25  0]
 [ 4  1 17 12  1  

Epoch 45
	Train loss: 0.072096
	Train class loss: 0.048352
	Train reg loss: 0.023744
	Validation loss: 0.024253
	Validation class loss: 0.000441
	Validation reg loss: 0.023812
	Top1 train accuracy: 0.386295
	Top5 train accuracy: 0.791667
	Top1 validation accuracy: 0.457286
	Top5 validation accuracy: 0.788945
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 13  3  2  0  0  2 29  0  1  0]
 [13  0  4  1  2  0  0  1  0 26  3  0]
 [ 2  1  7  5  3  1  0  0  2  0 28  1]
 [ 4  0 16 14  1  0  1  2  2  0  1  8]]
mbi=275348736
time= 6.623352
Epoch 46
	Train loss: 0.071879
	Train class loss: 0.048188
	Train reg loss: 0.023690
	Validation loss: 0.024200
	Validation class loss: 0.000441
	Validation reg loss: 0.023758
	Top1 train accu

Epoch 54
	Train loss: 0.071086
	Train class loss: 0.047607
	Train reg loss: 0.023479
	Validation loss: 0.024004
	Validation class loss: 0.000434
	Validation reg loss: 0.023571
	Top1 train accuracy: 0.397590
	Top5 train accuracy: 0.807731
	Top1 validation accuracy: 0.477387
	Top5 validation accuracy: 0.804020
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  6  0  0  0  0  2 33  0  1  0]
 [14  0  3  4  0  0  0  0  0  0 26  3  0]
 [ 3  1  6  5  0  4  0  0  0  2  1 27  1]
 [ 5  0 15 12  1  1  1  1  1  2  0  1  9]]
mbi=275348736
time= 6.807496
Epoch 55
	Train loss: 0.071128
	Train class loss: 0.047655
	Train reg loss: 0.023473
	Validation loss: 0.024000
	V

Epoch 63
	Train loss: 0.070977
	Train class loss: 0.047546
	Train reg loss: 0.023431
	Validation loss: 0.023957
	Validation class loss: 0.000434
	Validation reg loss: 0.023523
	Top1 train accuracy: 0.406878
	Top5 train accuracy: 0.812500
	Top1 validation accuracy: 0.492462
	Top5 validation accuracy: 0.804020
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  6  0  0  0  0  0  2 33  0  1  0]
 [15  0  3  4  0  0  0  0  0  0  0 27  1  0]
 [ 3  1  6  5  0  3  1  0  0  0  2  0 27  2]
 [ 5  0 15 10  1  1  0  1  1  1  2  0  1 11]]
mbi=275348736
time= 6.892095
lr reduced to 0.001000
Epoch 6

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


163 support_vectors for class 0
249 support_vectors for class 1
483 support_vectors for class 2
497 support_vectors for class 3
460 support_vectors for class 4
494 support_vectors for class 5
437 support_vectors for class 6
497 support_vectors for class 7
396 support_vectors for class 8
460 support_vectors for class 9
471 support_vectors for class 10
428 support_vectors for class 11
250 support_vectors for class 12
246 support_vectors for class 13
279 support_vectors for class 14
462 support_vectors for class 15
retraining last layer...
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Plain evaluation after retrain
	Best top1 validation accuracy: 0.628141
	Best top5 validation accuracy: 0.834171
	Best top1 cumul accuracy: 0.418868
	Best top5 cumul accuracy: 0.813836
	Best top1 ori accuracy: 0.510000
	Best top5 ori accuracy: 0.875000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.84      0.82      0.83        50
           1       0.52      0.78      0.62        50
           2       0.22      0.20      0.21        50
           3       0.29      0.24      0.26        50
           4       0.30      0.31      0.30        49
           5       0.25      0.12      0.16        50
           6       0.31      0.32      0.32        50
           7       0.25      0.04      0.07        50
           8       0.43      0.64      0.51        50
           9       0.33      0.26      0.29        50
          10       0.34      0.28      0.31        50
          11       0.19      0.17      0.18        47
          12

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.

SVM evaluation
	Best top1 validation accuracy: 0.582915
	Best top1 cumul accuracy: 0.412579
	Best top1 ori accuracy: 0.470000
	Report string of cumul dataset
              precision    recall  f1-score   support

           0       0.87      0.80      0.83        50
           1       0.65      0.66      0.65        50
           2       0.26      0.32      0.29        50
           3       0.24      0.10      0.14        50
           4       0.25      0.29      0.27        49
           5       0.18      0.16      0.17        50
           6       0.30      0.34      0.32        50
           7       0.16      0.06      0.09        50
           8       0.44      0.50      0.47        50
           9       0.37      0.40      0.38        50
          10       0.35      0.26      0.30        50
          11       0.24      0.38      0.29        47
          12       0.48      0.70      0.57        50
          13       0.74      0.80      0.77        50
          14       0.64      0.

/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/liy0f/.conda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Class batch pretrain evaluation (plain method)
	Train loss: 0.024322
	Train class loss: 0.000803
	Train reg loss: 0.023519
	Validation loss: 0.024767
	Validation class loss: 0.001249
	Validation reg loss: 0.023519
	Top1 train accuracy: 0.197398
	Top5 train accuracy: 0.414561
	Top1 validation accuracy: 0.000000
	Top5 validation accuracy: 0.000000
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0

Epoch 6
	Train loss: 0.084712
	Train class loss: 0.061697
	Train reg loss: 0.023015
	Validation loss: 0.023680
	Validation class loss: 0.000524
	Validation reg loss: 0.023156
	Top1 train accuracy: 0.191394
	Top5 train accuracy: 0.606955
	Top1 validation accuracy: 0.025126
	Top5 validation accuracy: 0.497487
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

Epoch 12
	Train loss: 0.083802
	Train class loss: 0.061104
	Train reg loss: 0.022698
	Validation loss: 0.023358
	Validation class loss: 0.000521
	Validation reg loss: 0.022838
	Top1 train accuracy: 0.203653
	Top5 train accuracy: 0.642232
	Top1 validation accuracy: 0.060302
	Top5 validation accuracy: 0.532663
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  

Epoch 18
	Train loss: 0.083316
	Train class loss: 0.060929
	Train reg loss: 0.022387
	Validation loss: 0.023015
	Validation class loss: 0.000491
	Validation reg loss: 0.022525
	Top1 train accuracy: 0.216913
	Top5 train accuracy: 0.652489
	Top1 validation accuracy: 0.135678
	Top5 validation accuracy: 0.643216
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  

Epoch 24
	Train loss: 0.082534
	Train class loss: 0.060452
	Train reg loss: 0.022083
	Validation loss: 0.022712
	Validation class loss: 0.000494
	Validation reg loss: 0.022218
	Top1 train accuracy: 0.233675
	Top5 train accuracy: 0.670503
	Top1 validation accuracy: 0.145729
	Top5 validation accuracy: 0.643216
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  

Epoch 30
	Train loss: 0.082044
	Train class loss: 0.060262
	Train reg loss: 0.021782
	Validation loss: 0.022397
	Validation class loss: 0.000481
	Validation reg loss: 0.021916
	Top1 train accuracy: 0.241931
	Top5 train accuracy: 0.680510
	Top1 validation accuracy: 0.130653
	Top5 validation accuracy: 0.668342
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  

Epoch 36
	Train loss: 0.081587
	Train class loss: 0.060100
	Train reg loss: 0.021487
	Validation loss: 0.022087
	Validation class loss: 0.000468
	Validation reg loss: 0.021619
	Top1 train accuracy: 0.259194
	Top5 train accuracy: 0.693520
	Top1 validation accuracy: 0.256281
	Top5 validation accuracy: 0.678392
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  

Epoch 43
	Train loss: 0.080725
	Train class loss: 0.059575
	Train reg loss: 0.021150
	Validation loss: 0.021748
	Validation class loss: 0.000467
	Validation reg loss: 0.021281
	Top1 train accuracy: 0.286715
	Top5 train accuracy: 0.706530
	Top1 validation accuracy: 0.281407
	Top5 validation accuracy: 0.693467
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  